### ISSUE TITLE
Problems with performing calculations (gem adds zeroes)

### ISSUE THREAD

**Issue by grammakov** [RubyMoney/money-rails#140]
Money gem keeps adding two zeroes to the end of my money figure (stored in cents) when I perform calculations on the row. Here's an example

``` ruby
2.0.0p247 :029 > c = Category.last
  Category Load (0.1ms)  SELECT "categories".* FROM "categories" ORDER BY "categories"."id" DESC LIMIT 1
 => #<Category id: 87, position: "2", name: "Category", created_at: "2013-11-14 15:18:33", updated_at: "2013-11-14 15:18:33", company_id: 24> ]
```

Let's see if it has transactions

``` ruby
2.0.0p247 :030 > c.transactions
  Transaction Load (0.1ms)  SELECT "transactions".* FROM "transactions" WHERE "transactions"."category_id" = ?  [["category_id", 87]]
 => #<ActiveRecord::Associations::CollectionProxy [#<Transaction id: 49, amount_cents: 50000, currency: "usd">]> 
```

It does, we can see 50 000 cents which is 500 bucks. Lets sum up and format that whole category

``` ruby
2.0.0p247 :031 > c.transactions.sum("amount_cents").to_money.format
   (0.1ms)  SELECT SUM("transactions"."amount_cents") AS sum_id FROM "transactions" WHERE "transactions"."category_id" = ?  [["category_id", 87]]
 => "50,000.00 $"
```

So is it a bug or am I doing something wrong?

**Comment by tncbbthositg** [comment]
It'd be neat if this thread was closed but also mentioned what would be the right way to sum a monetary field.

**Comment by ctilley83** [comment]
@tncbbthositg NO `how_to` for you!!!

**Comment by JamesChevalier** [comment]
I think you'd do this with `Money.new`, but I don't think this covers the issue of summing a column that has multiple currencies.

This would use your default currency on the entire sum (assuming you've set something like `config.default_currency = :usd` in `config/initializers/money.rb`):

```
Money.new(c.transactions.sum(:amount_cents))
```

This would force a single currency on the entire sum:

```
Money.new(c.transactions.sum(:amount_cents), 'USD')
```

This would use the currency for the first transaction on the entire sum (which could be a huge gamble unless you know that *all* of your transactions are the same currency):

```
Money.new(c.transactions.sum(:amount_cents), c.transactions.first.amount_currency)
```
