### ISSUE TITLE
How to convert a money object from one currency to another at runtime?

### ISSUE THREAD

**Issue by sachin87** [RubyMoney/money-rails#206]
Suppose i have a Booking model.

class Booking < ActiveRecord::Base

  register_currency :inr
  monetize :amount, as: :booking_amount

end

and i fetch a booking by doing

   b = Booking.first
   b.booking_amount.exchange_to(:usd)
it raises the error
    Money::Bank::UnknownRate: No conversion rate known for 'INR' -> 'USD'
1>as we know the exchange rate changes continuously, how to get correct exchange value?

2>Money object has a bank method with rates attributes do i need to do something with that?

**Comment by tommyalvarez** [comment]
@drunkonsound and after the initializer? (For example... if the user can update the rates through a form or settings page?)
