### ISSUE TITLE
Add support for rails_admin

### ISSUE THREAD

**Issue by cantonic** [RubyMoney/money-rails#216]
Hello,

I started using this gem since it is working with MongoID. Unfortunately integration in `rails_admin` is not that easy. I tried around for some time but couldn't find a solution which works fine with `rails_admin`.

It would be great if there was a field type for rails_admin. There is another gem called [mongoid_money_field](https://github.com/glebtv/mongoid_money_field) which [comes with rails_admin support](https://github.com/glebtv/mongoid_money_field/blob/master/lib/mongoid_money_field/rails_admin.rb) by defining a field type for it.

I would love to see the same for `money-rails`.

What do you think about my suggestion?

**Comment by yurijmi** [comment]
Would like to see this implemented.

**Comment by antstorm** [comment]
@yurijmi happy to review and merge a PR for that, you up for it?

**Comment by yurijmi** [comment]
Yeah, I'll see what I can do. Will make a PR when finished.

**Comment by antstorm** [comment]
@yurijmi thanks man and good luck!

**Comment by yurijmi** [comment]
@antstorm it's not like in mongoid_money_field. I really tried to make it recognize the Money type but i don't think it's possible here. Only manual field type ```:money```

**Comment by antstorm** [comment]
Maybe you can infer that automatically from `monetized_attributes` class variable?

**Comment by yurijmi** [comment]
Nah, the thing is that rails_admin factory for detecting fields only recognize fields from database. So I can't tell it to use ```:money``` for ```price``` field. The only field available to me is ```price_cents``` (or ```price_kopecks``` in my case, russian locale and stuff). So, only manual field setting :(
