### ISSUE TITLE
Rails 4.2 Migration helper raises wrong number of argument error

### ISSUE THREAD

**Issue by Adam89** [RubyMoney/money-rails#264]
I tried updating to rails 4.2 but encountered this error, it's caused by the below addition:

https://github.com/rails/docrails/blob/f6767b962e7dbcd2859a814ca1d369f0d5c064d2/activerecord/lib/active_record/connection_adapters/postgresql/schema_definitions.rb#L87

```
create_table :price_infos do |t|
   t.money :start_price
   t.money :final_price
   t.money :tax
 end
```
Raises a wrong number of argument error. 

```
== 20131119135443 CreatePriceInfos: migrating ==========================
-- create_table(:price_infos)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

wrong number of arguments (1 for 2)/Users/Adam/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_definitions.rb:87:in `money'
````

**Comment by simonoff** [comment]
@semmons99 no it's not related to #263. The issue what rails 4.2 support special type `money` in postgresql.

**Comment by semmons99** [comment]
Excellent. Thanks for figuring it out.

**Comment by Adam89** [comment]
Seems like this issue can now be closed :+1:
