### ISSUE TITLE
Money is not a module (TypeError)

### ISSUE THREAD

**Issue by malditojavi** [RubyMoney/money-rails#265]
Don't know if this a too noob question, but I'm struggling to solve this

` config/application.rb:9:in <top (required)>': Money is not a module (TypeError)`. I googled & stackoverflow'd for solutions to tackle this, but no results. Any idea how should I proceed?

**Comment by georgemillo** [comment]
Can you post the contents of your `application.rb` file?

**Comment by malditojavi** [comment]
Yes, here it is.

`require File.expand_path('../boot', __FILE__)`

`require 'rails/all'`

`Bundler.require(*Rails.groups)`

`module Money`
    `class Application < Rails::Application`
      `config.active_record.raise_in_transactional_callbacks = true`
    `end`
`end`

**Comment by georgemillo** [comment]
Is your Rails app called 'Money'? You can't call your Rails app that and use the `money` gem - they'll both try to create constants called `Money` which will conflict with each other. It's like trying to create an app called "String" or "Integer".

Closing this as the problem isn't `money-rails`'s.

**Comment by malditojavi** [comment]
Ops :( Thanks.
