### ISSUE TITLE
Gas Prices

### ISSUE THREAD

**Issue by davidlesches** [RubyMoney/money-rails#268]
Is there a way to use this with gas prices, which are to the third decimal, like $3.099. I want to store the price without rounding it up to two decimal places. How can I do this?

**Comment by semmons99** [comment]
`Money.infinite_precision = true` in a config file will get the underlying gem to store things with infinite precision.

**Comment by davidlesches** [comment]
thanks!

**Comment by davidlesches** [comment]
Doesn't seem to work, still rounds it to two decimal places

**Comment by semmons99** [comment]
You may need to change money-rails to use the underlying value or use the money gem directly. 

- shane
