### ISSUE TITLE
Mongoize broken in Rails <4.0

### ISSUE THREAD

**Issue by Walop** [RubyMoney/money-rails#272]
I'm using this gem in a project which is using Rails version 3.2 and saving prices broke after version 1.0.0 (at commit 4f82ad4 to be exact). I finally managed to track the problem and it seems to be switching in mongoid/money.rb from "symbolize_keys" to "deep_symbolize_keys" without backup option if "deep_symbolize_keys" method is not available.

**Comment by alup** [comment]
Can you provide the backtrace and the full error message you have observed?

**Comment by Walop** [comment]
There is no error or backtrace because the "if object.respond_to?(:deep_symbolize_keys!)" prevents deep_symbolize_keys! -method running for object if it is not available. After that the code tries to create a Money object with parameters "object[:cents], object[:currency_iso]", both being nil as the object hash has not been symbolized. Money's constructor happily makes an object with default values (0.0 and USD) when given nils and that is saved in the database. No error, no crash, no backtrace, just zero USD saved in the database.

**Comment by semmons99** [comment]
Sounds like we need an elsif, can you submit a quick PR? 

- shane

**Comment by greggroth** [comment]
This can be closed since #273 was merged
