### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by benliscio** [RubyMoney/money-rails#274]
Is it possible to update CHANGELOG.md with the changes since 0.12?

Thanks!

**Comment by semmons99** [comment]
Sure. Go ahead and I'll merge the PR. You'll just need to read back through the Git commits.

**Comment by georgemillo** [comment]
We should really insist that people update the Changelog when they make a PR.

**Comment by semmons99** [comment]
Could someone go through the commits? I'll start enforcing. 

- shane

**Comment by georgemillo** [comment]
I'll have a crack at it tomorrow.

**Comment by georgemillo** [comment]
Fixed by [cc2841]
