### ISSUE TITLE
Different behavior between Money.new and creating a new Mongoid document

### ISSUE THREAD

**Issue by romanlehnert** [RubyMoney/money-rails#281]
Steps to reproduce:
```ruby
class House
  include Mongoid::Document

  field :price, type: Money
end

Money.new(2000)
# => #<Money fractional:2000 currency:EUR>

House.new(price: 2000).price
# => #<Money fractional:200000 currency:EUR>
```

In my eyes, instantiating a new House with the param ```price: 2000``` for the Money-field "price" should behave same like instantiating a new Money with the same value as param. Did i understand it wrong?

**Comment by georgemillo** [comment]
I don't know much about how Mongoid works, but this wouldn't be unusual for ActiveRecord, as an AR model would have (using the default names) a `price_cents` attribute with a `price` getter and setter:

    House.new(price: 2000).price.format # => "€2000.00"
    House.new(price_cents: 2000).price.format # => "€20.00"

It seems inconsistent to me to make the line `House.new(price: 2000).price` have different behaviour depending on whether `House` is an ActiveRecord model or a Mongoid document.

Whatever the case, there's no practical way this could be changed now as it would break all existing apps which use money-rails with Mongoid.

**Comment by semmons99** [comment]
@romanlehnert you might be better server directly using the Money gem yourself. Or perhaps coming up with an alternate implementation of money-rails called mongo-money or something. I'd gladly merge it into the org so it get's attention.
