### ISSUE TITLE
Currency column not being set with the money instance's currency

### ISSUE THREAD

**Issue by jfelchner** [RubyMoney/money-rails#284]
The README is a little sparse on this so maybe I'm just doing it wrong.

I have this in my model:

```ruby
monetize :buy_price_cents
```

When, elsewhere in my code, I call:

```ruby
my_model_instance.buy_price = Money.new(100, 'USD')
```

My assumption would be that:

```ruby
my_model_instance.buy_price_currency
# => USD
```

But instead it's `nil`.

I'm making the assumption that `monetize`'s default behavior is to chop off the `_cents` from the field name and replace it with `_currency`.

**Comment by jfelchner** [comment]
Also, even when I set:

```ruby
monetize :auction_price_cents, :with_currency => :auction_price_currency
```

which I definitely do _not_ want to have to do on _every_ currency field, I get:

```
RuntimeError:
  Can't change readonly currency '' to 'USD' for field 'auction_price'
```

**Comment by semmons99** [comment]
Pretty sure it's just `buy_price.currency`

**Comment by jfelchner** [comment]
@semmons99 right, but I want it saved back to my model in the `buy_price_currency` column.

I guess my question is that if `monetize` knows that `buy_price_cents` is the name of my subunit column, does it not have a convention to assume that if it's not specified otherwise, to save the currency to `buy_price_currency`?

Or am I going to have to specify `:with_model_currency` on every `monetize` call?

**Comment by semmons99** [comment]
you should definitely have a _currency column in the DB if you've used the migration helper which is where it'll be saved

**Comment by jfelchner** [comment]
@semmons99 this is a legacy schema so we didn't use the migration helper, but we do have:

```sql
    buy_price_cents integer,
    buy_price_currency character varying(3),
```

as columns in our table.  Which should be correct.

**Comment by semmons99** [comment]
That sounds right. @alup are we missing something?



- shane

**Comment by semmons99** [comment]
Closed due to inactivity.

**Comment by jfelchner** [comment]
@semmons99 I'm not sure what "activity" I was expected to provide. :smile:  This is still a problem.
