### ISSUE TITLE
undefined method `silence_core_extensions_deprecations=' for Money:Class (NoMethodError)

### ISSUE THREAD

**Issue by allenwlee** [RubyMoney/money-rails#289]
received the above error upon trying to start server via `foreman` after:

updated from rails 4.0.0 to 4.2.0
Installing monetize 1.1.0 (was 0.1.4)
Installing money-rails 1.3.0 (was 0.9.0)

full gem update log [here](https://gist.github.com/allenwlee/993c943cb93c641ea9c9)
full error log [here](https://gist.github.com/allenwlee/415ceed549ab434f74d8)

**Comment by semmons99** [comment]
Looks like you're calling it in your initializer. Check this: https://github.com/RubyMoney/money-rails/blob/03d526f29ec8651f9d79dcc9a08d2c857b41837a/spec/spec_helper.rb#L13

**Comment by allenwlee** [comment]
thanks for responding.  i'm a bit new to this, could you expand on what a solution would be?  i've googled initializer and this is the first line in config/applications.rb
```
require File.expand_path('../boot', __FILE__)
```
and this is in my boot file:
```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)

require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
```

how would I exclude only this gem from this current structure?
thanks

**Comment by allenwlee** [comment]
ok I believe I solved the problem.  I basically just commented out the line 
```

**Comment by semmons99** [comment]
Closed due to inactivity.
