### ISSUE TITLE
How do I load money-rails properly outside of rails?

### ISSUE THREAD

**Issue by konung** [RubyMoney/money-rails#291]
Hello.

### Background: 

I'm trying to use Money-rails out side of rails. Specifically I'm using praxis framework ( it's ruby based api framework - https://github.com/rightscale/praxis ) . Obviously it's not rails  - However I'm using ActiveRecord 4.2 as my ORM and ActiveSupport as well 4.2 . My DB is MySQL 5.5 . I'm able to use other ActiveRecord related gems like ransack, caminari & standalone_migrations

### Problem
Even thou money-rails gets loaded in my environment - when I try to do: 

````ruby
class SalesOrderLine < ActiveRecord::Base
   .....
   monetize :price_cents

end
````

I get:
````ruby
NoMethodError: undefined method `monetize' for #<Class:0x007f9e4f731d48>
````
Any suggestions?

### Temporary solution

I sidestepped the issue for now like so, so I know Money and Monetize gems are loaded and working properly

````ruby
  def price
    Money.new(self.price_cents)
  end

  def price=amount
    self.price_cents = Monetize.parse(amount).cents
  end
````

**Comment by semmons99** [comment]
My guess, off-hand, is there's some autoloading happening in rails and not praxis. I think you just need to do this: https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails.rb#L13

**Comment by stevenbarragan** [comment]
Same problem here, @konung did you find a solution?

**Comment by stevenbarragan** [comment]
I was having problems to test my gem (where I'm using ``money-rails``)

I put this into an initializer and it works, I hope it helps

```ruby
MoneyRails::Hooks.init
```

**Comment by semmons99** [comment]
Closed due to inactivity.
