### ISSUE TITLE
Not a number validation error

### ISSUE THREAD

**Issue by bismark64** [RubyMoney/money-rails#293]
Hi guys, having a validation error when trying to save monetized fields.
I'm using money-rails 1.3.0 and money 6.5.1 and this is my model extract:

```ruby 
class Coupon < ActiveRecord::Base
  monetize :unit_donation_cents
  monetize :total_donation_cents
end
```

When trying to save this coupon object:
```bash
<Coupon id: nil, title: "Test Coupon", created_at: nil, updated_at: nil, unit_donation_cents: 0, unit_donation_currency: "USD", total_donation_cents: 0, total_donation_currency: "USD">
```
I get this:

```bash
{:unit_donation=>["is not a number"], :total_donation=>["is not a number"]}
```
This was working with a previous version of both money and money-rails gems.
What am I missing?
Thanks!

**Comment by semmons99** [comment]
Could you test vs master?



- shane

**Comment by denyago** [comment]
Same issue.

```ruby
m = Mapping.new(price: '1.00 EUR')
m.valid? # false
m.errors.full_messages 
# "Price is not a number"
```

```
class Mapping < ActiveRecord::Base
  monetize :price_cents, as: :price,
                         numericality: {greater_than_or_equal_to: 0},
                         with_model_currency: :price_currency
```

```
money (6.5.1)
money-rails (1.4.1)
```

**Comment by semmons99** [comment]
Closed due to inactivity.

**Comment by KelseyDH** [comment]
I'm getting a problem almost identical to this.   It seems to be triggered when a field has multiple money columns?

In my case I have these columns:
```
<Goal:0x00007feaad404b70> {
                          :id => xx,
                       :title => "Long term Savings",
                    :due_date => Thu, 01 Feb 2018,
                     :user_id => 237,
           :recipient_user_id => nil,
                    :position => nil,
                  :percentage => 15,
            :repeat_option_id => nil,
         :autosave_start_date => nil,
                :goal_type_id => 2,
                :autotransfer => true,
                :amount_cents => nil,
             :amount_currency => nil,
        :current_amount_cents => nil,
     :current_amount_currency => nil,
       :autosave_amount_cents => nil,
    :autosave_amount_currency => nil
```

I have a numericality validation for a separate field called `percentage`, nothing radical.

Yet this fails on a basic instantiation using:

```
  monetize :amount_cents
  monetize :current_amount_cents
  monetize :autosave_amount_cents
```

And hacks like using `with_model_currency:` aren't helping either.

----------

 With this issue, combined with scary issues pointed out by others in how this app does floating point math... and I'm beginning to question the sanity of using this library over just risking the occasional rounding error using decimals.

Inexplicable and unexplainable callback magic... on a field dealing with money fields... is about the last thing a maintainable rails app wanting to safely deal with money should want to deal with.

**Comment by antstorm** [comment]
@KelseyDH what are the errors you're seeing when performing validation? I'll have a look into what's wrong here.

I agree that this library has gone too far along the magic route, but as far as I know it always preferred plug-in-play approach over a thoughtful integration. The problem comes when trying to unwind the magic while supporting all the existing features. If you have thoughts on what could be done better — I'd love to hear them.

**Comment by noelrappin** [comment]
I am also seeing this error on Money 6.10.1, monetize 1.7.0 and Money-Rails 1.10 and Rails 4.2

I think it may be related to a record with multiple money fields and also to a field with a default of zero in the database but which has not been set yet -- ActiveRecord will tell you the field is zero, but the money-rails validation fails. I'll try and get a minimal sample here if I can

**Comment by gvpmahesh** [comment]
You can circumvent this issue by providing allow_nil to true
`monetize :bla_bla_bla_cents, :allow_nil => true`

**Comment by ClaudioFloreani** [comment]
> You can circumvent this issue by providing allow_nil to true `monetize :bla_bla_bla_cents, :allow_nil => true`

I've lost a whole morning inspecting this issue just to find out that `:allow_blank` is not allowed on monetize. After changing it to `:allow_nil`, everything is fine.
