### ISSUE TITLE
Identity element (Money.new(0)) has currency and causes conversion error

### ISSUE THREAD

**Issue by sktoiva** [RubyMoney/money-rails#296]
Currently, ```Money.new(0)``` instantiates the money object with default currency and when doing basic arithmetic with ```+``` and ```-``` this might raise an error. 

In an application that has multiple possible currencies an identity element without currency would do calculations easier with default values. Now, it is necessary to check presence and handle the situation with conditionals.

For instance, I would like to do the following:
```ruby
def calculate_total(item_price, item_quantity = 1, shipping_price = Money.new(0))
   item_price * quantity + shipping_price 
end
```
instead of:
```ruby
def calculate_total(item_price, item_quantity = 1, shipping_price)
   if shipping_price.nil?
     item_price * quantity
   else 
     item_price * quantity + shipping_price
   end 
end
```

**Comment by semmons99** [comment]
@sktoiva I'd gladly merge a patch that adds a currency-less version of Money.new(0). We've had discussion before around this, but no one followed through.

**Comment by sktoiva** [comment]
Actually, just noticed that the newest version of money gem has the arithmetic working properly. So, going to close this.
