### ISSUE TITLE
Validate numericaly

### ISSUE THREAD

**Issue by oprema** [RubyMoney/money-rails#305]
Hi,

in a model I have a validation like that:
```
monetize :monthly_cents, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
```
To test it I use a rails console
First I instantiate an object p and do
```
p.monthly_cents = 3
p.valid? => true
p.monthly_cents = 6
p.valid? => false
```
as it should be
If I do the same with
```
p.monthly = Money.new(3, 'EUR')
p.valid? => false
```
Am I doing something stupid or is this a validation bug?
I am on Rails 4.2 with postgresql and have read the notice

**Comment by semmons99** [comment]
can you `puts` what the value of `monthly_cents` is after that?

**Comment by antstorm** [comment]
It seems to be a valid behaviour, since `numericality` validates full value (not cents). So in you case `Money.new(3)` is actually €0.03 and is not valid.

It is kinda confusing. You can try `subunit_numericality` instead, which validates cents.

**Comment by oprema** [comment]
Big thanks to @antstorm and all the others who answered. Yep, I agree, this was not clear to me but subunit_numericality  did the trick.
