### ISSUE TITLE
Setting currency at the user level

### ISSUE THREAD

**Issue by noctivityinc** [RubyMoney/money-rails#306]
This is a great gem but I cant find any documentation or wikis on how to implement USER level currency.  I have a user model with a currency field.  Im using the currency_select gem to let the user select their currency.

My products model has a price_cents and price_currency field, in case they change their default currency later.

But how do I change their sessions currency based on the selected currency?  I understand I can pass @user.currency whenever I save the price, but what about things like the currency_symbol helper, which I believe reads the default currency only.  How do we use that?

**Comment by semmons99** [comment]
We don’t have a concept of a session currency (to my knowledge). Sounds like something you need to either create a helper method for or submit a patch if you think it would be useful for others. :smile:

**Comment by ajhodges** [comment]
+1

**Comment by semmons99** [comment]
Closed due to inactivity.
