### ISSUE TITLE
Form Helper?

### ISSUE THREAD

**Issue by lifeiscontent** [RubyMoney/money-rails#309]
Is the a form helper collection for all the currencies I can pass to a select like I can do with a timezone?

**Comment by semmons99** [comment]
Nope. 



- shane

**Comment by lifeiscontent** [comment]
Any objection to making one? @semmons99

**Comment by semmons99** [comment]
Nope. Go for it. 



- shane

**Comment by semmons99** [comment]
Closed due to inactivity.
