### ISSUE TITLE
can't allow nil values

### ISSUE THREAD

**Issue by albertobissacco** [RubyMoney/money-rails#311]
I have the Product model and set like this:
```ruby
class Product < ActiveRecord::Base
  monetize :price_cents, :allow_nil => true
end
```

```ruby
class CreateProducts < ActiveRecord::Migration
  def change
    create_table :products, id: :uuid do |t|
      t.monetize :price, null: true, default: nil
      t.string :currency
    end
  end
end
```

I tried to drop the db, recreate the Schema.db and migrating few times but i still have the default value = 0 when i create new product:
```ruby
Product.new
# => #<Product id: nil, price_cents: 0, price_currency: "EUR", currency: ni, created_at: nil, updated_at: nil>
```

What am i doing wrong?

**Comment by antstorm** [comment]
@albertobissacco in case this is still relevant, can you paste your `products` table description from the database?

**Comment by semmons99** [comment]
Closed due to inactivity.

**Comment by JamesChevalier** [comment]
The problem here is that this does not respect the `null: true, default: nil` parameters:

```ruby
t.monetize :price, null: true, default: nil
```

You *must* use [the syntax from the README](https://github.com/RubyMoney/money-rails#allow-nil-values):

```ruby
add_money :products, :price, amount: { null: true, default: nil }
```

...or if [you're using PostgreSQL](https://github.com/RubyMoney/money-rails/issues/322):

```ruby
add_monetize :products, :price, amount: { null: true, default: nil }
```
