### ISSUE TITLE
monetize validation fails in subclasses deeper that one level

### ISSUE THREAD

**Issue by rosskevin** [RubyMoney/money-rails#314]
This was a past change to fix finding `monetized_attributes` that should be inherited:
https://github.com/RubyMoney/money-rails/commit/5c526b0ecdab75f6dd189cccc959f80102e714f9

Unfortunately, this fails when subclassing is deeper than one level.

```ruby
TypeError: nil is not a symbol nor a string
money-rails-1.3.0/lib/money-rails/active_model/validator.rb:18:in `public_send'
money-rails-1.3.0/lib/money-rails/active_model/validator.rb:18:in `validate_each'
```

The [subunit_attr](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_model/validator.rb#L18) is null, presumably because [this code does not climb](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L15) the hierarchy looking for `respond_to?(:monetized_attributes)`.

I'll take a shot at a fix.

**Comment by rosskevin** [comment]
I've created an addition to monetize_spec to test it, and it works.  I just noticed that 1.3.0 was the last release just prior to the fix listed above.

**Comment by semmons99** [comment]
If you'd like a release after this, I'll gladly roll one.

**Comment by rosskevin** [comment]
I'm using master and it seems to work fine.  I'm not sure my additional test adds value (since it didn't prove anything new) so I'll just delete my fork.  I think you are good to go for a new release.

**Comment by semmons99** [comment]
1.4.0 released

**Comment by rosskevin** [comment]
Actually, I think I've found a problem, still working it out, but it seems that [the validator code](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_model/validator.rb#L9) is expected `@attr` to be a string, when it is a symbol to start with (or at least in some situations).  The problem lies in that (sometimes, again not sure when just getting into this) that the hash keys are strings not symbols, so the result of the call is null and yields `TypeError: nil is not a symbol nor a string`.

Perhaps there is an inconsistency using hash keys vs strings, but I see the following only in some cases (again, not sure why my case triggers it):

```ruby
@attr == :tax_amount
@record.class.monetized_attributes # 'tax_amount' => tax_amount_cents

subunit_attr = @record.class.monetized_attributes[@attr.to_sym] # nil - existing code
subunit_attr = @record.class.monetized_attributes[@attr.to_s] # "tax_amount_cents"
```

I'lll take a look deeper, but seems to be inconsistent use/creation of keys.

**Comment by semmons99** [comment]
Thanks. Let me know what you find. 



- shane

**Comment by rosskevin** [comment]
Push #315 submitted with resolution
