### ISSUE TITLE
Non-intuitive comparison checks

### ISSUE THREAD

**Issue by reustmd** [RubyMoney/money-rails#316]
I find the comparison with 0 to be a bit surprising.

What happens:
0 > 1.to_money ==> true
1 > 1.to_money ==> false

What I'd expect:

0 > 1.to_money ==> false
1 > 1.to_money ==> false

**Comment by semmons99** [comment]
You probably want to open this issue on the `money` gem itself, not this repo which is rails specific wrappers.
