### ISSUE TITLE
Wrong ARS symbol

### ISSUE THREAD

**Issue by brunitob** [RubyMoney/money-rails#320]
Hi guys, I detected a wrong symbol on ARS Argentinian Pesos, 

https://github.com/RubyMoney/money/blob/master/config/currency_iso.json
```
"ars": {
    "priority": 100,
    "iso_code": "ARS",
    "name": "Argentine Peso",
    "symbol": "$",
    "disambiguate_symbol": "$m/n",
    "alternate_symbols": ["$m/n", "m$n"],
    "subunit": "Centavo",
    "subunit_to_unit": 100,
    "symbol_first": true,
    "html_entity": "&#x20B1;",
    "decimal_mark": ",",
    "thousands_separator": ".",
    "iso_numeric": "032",
    "smallest_denomination": 1
  },
```
The problem is  "html_entity": "&#x20B1;" is not the same as "symbol": "$".

Check http://graphemica.com/%E2%82%B1

**Comment by semmons99** [comment]
Please submit a patch to the money gem to update this.
