### ISSUE TITLE
Millionth's instead of Cents

### ISSUE THREAD

**Issue by markalanevans** [RubyMoney/money-rails#323]
## Use Case
We sell data usage, and the cost can be fractions of a penny per data point.
So ideally instead of multiplying by 100 to get the dollar value in cents, we would like to multiply by 1,000,000 to store it in 1000th of a cent.   .01/1000  plus an extra decimal just in case.

#### Ex:
Initial Value: $23.52348 stored as 23523480
Sell 30 data points @ .00001 * 1,000,000 = 10.  x 30 = 300

```
 23523480
-     300
________
23523180

~ = 23.52318
```

I'd like to use this logic both inside and outside of a Rails App.

Thoughts?
Is there a configuration on your end that supports this?

Thanks very much,

-Mark

**Comment by semmons99** [comment]
Look into the infinite precision option in the base money gem



- shane

**Comment by markalanevans** [comment]
@semmons99 did you find any docs on it? I see mention of it in some commits and there is a flag  I see. Have you used it?

**Comment by semmons99** [comment]
Yes. I've used it. You'll need to experiment. 



- shane

**Comment by semmons99** [comment]
Closed due to inactivity.
