### ISSUE TITLE
0 in any currency should eq 0?

### ISSUE THREAD

**Issue by brightbits** [RubyMoney/money-rails#325]
```ruby
Money.new(0, "GBP") == 0
# => true
Money.new(0, "CAD") == 0
# => false
```

This doesn't make sense to me?

**Comment by antstorm** [comment]
Can you provide a bit more details on what version of `money` you are using?

Just tried this and it's `true` in both cases.

**Comment by brightbits** [comment]
Sorry, 1.3.0

**Comment by antstorm** [comment]
No worries! That's `money-rails` version, but the issue seems to be with the `money` gem (yes, these are two different things). Can you paste it's version as well?

**Comment by brightbits** [comment]
Hi @antstorm. We are using version `6.5.1` of the money gem :)

**Comment by crftr** [comment]
@brightbits this could be related to the configured default currency.

For this quick test:
```ruby
require 'money-rails'

puts "Which currencies satisfy Money.new(0, \"Currency\") == 0"
puts "# => " + Money::Currency.all.map(&:iso_code).select { |iso_code| Money.new(0, "#{iso_code}") == 0 }.to_s

puts "Default currency"
puts "# => " + MoneyRails.default_currency.iso_code

exec 'gem list money'
```

I'm generating an output of:
```
Which currencies satisfy Money.new(0, "Currency") == 0
# => ["USD"]
Default currency
# => USD

*** LOCAL GEMS ***

money (6.5.1)
money-rails (1.3.0)
```

**Comment by crftr** [comment]
Further, [look at how Money defines `==`](https://github.com/RubyMoney/money/blob/master/lib/money/money/arithmetic.rb#L26)

Because 0 (a Fixnum) responds to `to_money`, it will be coerced to a Money instance of your default currency prior to the actual comparison.

**Comment by crftr** [comment]
Actually, before going too much further...

@brightbits, what's your motivation for this issue?  Is it purely philosophical or do you have a use-case in mind?

**Comment by brightbits** [comment]
Checking if a product was free, and it broke because the products price was in a different currency to the default (so it seems). Seems a bit counter intuitive for 0 in any currency to not be == 0. Principle of least surprise and all that?

Thanks

**Comment by crftr** [comment]
I hear you.  In the short-term, comparing the fractional values would be an option
```ruby
Money::Currency.all.map(&:iso_code).select { |iso_code| Money.new(0, "#{iso_code}").fractional == 0 }
# => returns all currencies
```

**Comment by brightbits** [comment]
Yeah this is what I ended up with, it just seems wrong.

Cheers

**Comment by crftr** [comment]
This will be resolved in the next release of the Money gem.
