### ISSUE TITLE
Accept lambda or method for 'register_currency'

### ISSUE THREAD

**Issue by drale2k** [RubyMoney/money-rails#328]
Hi,

is there any way i can make ````register_currency```` take a dynamic value? Storing the currency in a db column is not an option in our case and i tried using ````with_currency```` and passing it a method (which works) but the problem was that the currency symbol did not update on the front end (i passed it EUR but it still showed in USD $).

````register_currency```` works perfectly for us when we try it and pass a hard coded symbol value but we need to pass it a dynamic value.

Thanks

**Comment by semmons99** [comment]
@RubyMoney/money-rails-devs can anyone help @drale2k here?

**Comment by antstorm** [comment]
@drale2k I'm afraid currently there's no way of doing that using `register_currency`, but this is something we can definitely improve in the future.

On the other hand `with_currency` approach should work. Can you paste some code here? Particularly interested in `monetize` call on the model and rendering of the `Money` object.

**Comment by drale2k** [comment]
Thanks for the quick reply. 

The model 'registrations' 

````
monetize :total_price_cents, with_currency: :set_currency

def set_currency
  site.currency
end
`````

In the view to show the price. This works when using ````register_currency```` 
````= @registration.balance.format ````

**Comment by antstorm** [comment]
@drale2k right, so the issue is that you are using `with_currency` option, which expects a column named `set_currency`. What you need is `with_model_currency`.

**Comment by semmons99** [comment]
Closed due to inactivity.
