### ISSUE TITLE
increment method does not work

### ISSUE THREAD

**Issue by DmitryKK** [RubyMoney/money-rails#330]
My code:

```
class Account < ActiveRecord::Base
  monetize :amount, as: :money_amount
end
```
where `amount` has integer type

when i run code:
```
Account.first.increment!(:money_amount, 100)                                                                                                                                                 
```
i get error:
```
ActiveModel::MissingAttributeError: can't write unknown attribute `money_amount`
from /Users/dmitrij/.rvm/gems/ruby-2.2.2@my_app/gems/activerecord-4.2.0/lib/active_record/attribute.rb:124:in `with_value_from_database'
```

I use Rails 4.2.0

**Comment by antstorm** [comment]
@DmitryKK I know this might be a bit confusing, but the first parameter that you pass to the `monetize` call is the name of the column used for persisting money value, which is `amount` in your case. So if you could pass it to the `increment!` call, it should work:

`Account.first.increment!(:amount, 100)`

**Comment by DmitryKK** [comment]
Thanks for answer. I got new error:

```
Account.first.increment!(:amount, Money.new(10, :USD)) 
NoMethodError: undefined method `exchange_to' for #<BigDecimal:7ff2e922b5a8,'0.40001E6',9(18)>
from /Users/dmitrij/.rvm/gems/ruby-2.2.2@my_app/gems/money-6.5.1/lib/money/money/arithmetic.rb:85:in `+'
```

**Comment by antstorm** [comment]
@DmitryKK `increment!` is a method that acts on an integer value of the specified column. It won't do any currency conversion for you, so if you simply want to increment the amount by 10 cents, run this:

`Account.first.increment!(:amount, 10)`

If you want to add 10 cents to the value which might be in a different currency, do this:

`Account.first.money_amount += Money.new(10, :USD)`

**Comment by DmitryKK** [comment]
ok, I understand. thanks
