### ISSUE TITLE
stack level too deep on model save

### ISSUE THREAD

**Issue by gswartz777** [RubyMoney/money-rails#334]
I am getting the following error when my model is trying to be saved.

  /Users/user/Code/app/src/vendor/cache/money-rails-541b674a6b34/lib/money-rails/active_record/monetizable.rb:111:in `block (2 levels) in monetize'
  /Users/user/Code/app/src/vendor/cache/money-rails-541b674a6b34/lib/money-rails/active_record/monetizable.rb:111:in `public_send'

Here is my model code.

module BBH
  class JobSearch < ActiveRecord::Base
    monetize :salary, as: 'salary', allow_nil: true
    DEFAULT_DISTANCE_IN_MILES = 50

    def search(page, page_size) 
        fulltext keyword
        paginate page: page, per_page: page_size
      end
    end
  end
end

I am using the latest version of monetize.  Any idea how to fix this?

**Comment by antstorm** [comment]
@gswartz777 The issue here is the way you call the `monetize` method — the first argument should be the DB column, which usually includes `_cents` postfix.

**Comment by gswartz777** [comment]
Thank you!
