### ISSUE TITLE
Sorting by monetize field

### ISSUE THREAD

**Issue by DmitryKK** [RubyMoney/money-rails#337]
Hello. I have model:
```
class Company < ActiveRecord::Base
  monetize :base_price, as: :money_base_price, with_model_currency: :currency
...
end
```

And I'd like to sort companies by `money_base_price` field

But if i do:

`Company.order(:money_base_price)`

then i get error:

`PG::UndefinedColumn: ERROR:  column companies.money_base_price does not exist`

Is it possible what I want?

Thank in advance.

**Comment by antstorm** [comment]
@DmitryKK when composing a SQL query you can use only actual DB columns. From your `monetize` definition it seems like the column is named `base_price`, so try `Company.order(:base_price)`.

Note that it won't take currency into account.

**Comment by DmitryKK** [comment]
The `base_price` has a different currency for different companies, so sorting by base_price is wrong. I want to sort into account currency.

**Comment by antstorm** [comment]
In that case you probably have 2 options:

1. If the Company table is not big, you can sort it in your code using `.sort(&:money_base_price)`
2. Store either an exchange rate or exchanged price in your table and use it in your `order` call

**Comment by DmitryKK** [comment]
The second option is good. Thanks
