### ISSUE TITLE
Creating my own ActiveRecord datatype

### ISSUE THREAD

**Issue by sps196** [RubyMoney/money-rails#338]
Hi,

This isn't a money-rails issue as such.. I've been trying to figure out how to create my own rails datatype, in the same way as you have done. But I can't figure out how it's done, despite having dug through your sourcecode.. Can you point me towards the areas I should look at please?

Sam

**Comment by antstorm** [comment]
@sps196 take a look at `lib/money-rails/active_record/migration_extensions/` directory

**Comment by sps196** [comment]
Thanks, I'll check it out.

2015-06-28 11:06 GMT+01:00 Anthony Dmitriyev <notifications@github.com>:

**Comment by semmons99** [comment]
Closed due to inactivity.
