### ISSUE TITLE
Preserve user input (type cast prolem?)

### ISSUE THREAD

**Issue by vemperor** [RubyMoney/money-rails#341]
Let's say I have some model using monetize.
Case 1:
monetize :price, allow_nil: true

Happy user/admin types something like "asdf", gets error "not a number". But now user input "asdf" replaced by "0.00" (which is, as far as I dig it, typecasting from blank string).

Case 2:
monetize :price, allow_nil: true, disable_validation: true
Same user input. No validations (by design) and expected value is "nil", but we get "0.00".

For now I have a workaround using
```ruby
object.send("#{attribute_name}_money_before_type_cast")
```
something like this (I use simple_form for this): https://gist.github.com/vemperor/9b48dcd946232a2fcebb

The question is if described above happens "by design" or is an actual issue (I suggest the last).

**Comment by semmons99** [comment]
It's by design based on user request, but you could submit a PR to ensure failed validations don't change the input.

**Comment by bertBruynooghe** [comment]
@semmons99 Looks a bit weird to me that the default implementation changes the inputs, as one of the most important guidelines on UI is to maintain user input. It looks like some setting like bootstrap-datepicker's ```forceParse```, which by default should be false...

**Comment by bertBruynooghe** [comment]
Patched this issue in our projects with following code:

```# There is one side effect to this patch: although '0.0' is probably wrong input considered by a few locales,
# it will be considered to be correct here.
ActiveSupport.on_load(:active_record) do
  class << self

    #redefining monetize method
    def monetize_with_proper_usability(*args, &block)
      monetize_without_proper_usability(*args, &block)

      attr_name = args.first.to_s.gsub(/#{MoneyRails::Configuration.amount_column[:postfix]}$/, "")

      #redefining attribute reader
      define_method("#{attr_name}_with_proper_usability") do
        resource = self
        result = send(:"#{attr_name}_without_proper_usability")
        if result
          value_before_type_cast = resource.send("#{attr_name}_money_before_type_cast")
          zero_input = (value_before_type_cast == 0.0)
          invalid_input = result.fractional == 0.0 && !zero_input
          if invalid_input
            #redefining string conversions
            result.define_singleton_method(:to_s) { value_before_type_cast }
            result.define_singleton_method(:format) { |_| value_before_type_cast }
          end
        end
        result
      end
      alias_method_chain attr_name, :proper_usability
    end

    alias_method_chain :monetize, :proper_usability
  end
end
```
 I am willing to write a PR if there's a clear view on how this mode/the previous mode should be enabled...

**Comment by semmons99** [comment]
Closed due to inactivity.
