### ISSUE TITLE
0 - Money Object gives a positive Money Object

### ISSUE THREAD

**Issue by adityan-webonise** [RubyMoney/money-rails#343]
I have set USD as my default Currency type with cents.
When I do the following,

a = Money.new(1)
 => Money fractional:100 currency:USD
0 - a
 => Money fractional:100 currency:USD
The result is strangely still a positive money object.
And,
- a
 => Money fractional:-100 currency:USD

Which is correct.

I am having to compare after converting Money Object to integer now!

**Comment by antstorm** [comment]
It definitely seems like a bug, although if you do:

```
b = Money.new(0) - a
=> <Money fractional:-1 currency:GBP>
```

You get the right result. The comparison works because it's `=>` (greater or equals), it you do just `>` it won't pass.

**Comment by antstorm** [comment]
I'm also slightly surprised that `0 - a` gives you an instance of `Money`, because it calls the `-` method on `Numeric` class that has nothing to do with `Money`

**Comment by adityan-webonise** [comment]
Thanks @antstorm Yeah it seems strange. Just with numeric operation it gives strange results. And 0 - a is indeed giving me a money object.
Also, just for heads up, if I do 1 - a, it throws an error. Which seems fine.

**Comment by antstorm** [comment]
Hmm… right, so probably it calls this method (from `money` gem `/lib/money/money/arithmetic.rb`):

```ruby
def -(other_money)
  return self if other_money == 0
  other_money = other_money.exchange_to(currency)
  Money.new(fractional - other_money.fractional, currency)
end
```

In case `other_money` is zero, it just returns `self`.

**Comment by antstorm** [comment]
I also found this — https://github.com/RubyMoney/money/commit/f808668509b5ebaf0511118e0fb33c629744e1c3 that seems to include a fix for the problem you've described.

@semmons99 why wasn't it ever merged?

**Comment by semmons99** [comment]
No one reviewed or helped with the PR, so we didn't merge it. Feel free to revive it and try to get it merged. 



- shane

**Comment by adityan-webonise** [comment]
@antstorm In the PR it seems like it would throw an error if we compare it with some integer. But it would return self if other_money == 0
Thanks for a really quick reply though

**Comment by antstorm** [comment]
@adityan-webonise yeah, I'll take a closer look at that PR and see what needs to be done before we can merge it

**Comment by adityan-webonise** [comment]
@antstorm Thanks a ton!

**Comment by antstorm** [comment]
@adityan-webonise I've resurrected the PR. It will throw `TypeError` whenever object types don't match and ruby falls back to calling `coerce` method.

Although it won't throw an error when doing `==` and `===` directly, because in that case ruby doesn't call `coerce`.

**Comment by semmons99** [comment]
Closed due to inactivity.
