### ISSUE TITLE
Numericality validation custom error message ignored

### ISSUE THREAD

**Issue by haraldkrischner** [RubyMoney/money-rails#344]
When I setup my validation like the example I do not get my custom error message – instead I get the default greater_than error message.

    monetize :price_in_cents,
           as: :price,
           numericality: {
               greater_than: 0.10,
               message: "custom message"
           }

Using: money-rails 1.4.1, rails 4.2

Greetings

**Comment by semmons99** [comment]
Closed due to inactivity.
