### ISSUE TITLE
instance currency is not working in production on Rails3.2.21

### ISSUE THREAD

**Issue by kevin-jj** [RubyMoney/money-rails#345]
It works in development on Rails3.2.21 but not in production.

Exception:

missing attribute: unit_price_currency
money-rails (1.4.1) lib/money-rails/active_record/monetizable.rb:202:in `public_send'

money-rails (1.4.1) lib/money-rails/active_record/monetizable.rb:202:in `public_send'
money-rails (1.4.1) lib/money-rails/active_record/monetizable.rb:202:in `block (2 levels) in monetize'
money-rails (1.4.1) lib/money-rails/active_record/monetizable.rb:114:in `public_send'
money-rails (1.4.1) lib/money-rails/active_record/monetizable.rb:114:in `block (2 levels) in monetize'
app/views/layouts/application.html.erb:126:in `block in _app_views_layouts_application_html_erb__4062930295657530274_55845260'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:6:in `each'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:6:in `each'

eviorment:
Rails 3.2.21
money-rails 1.4.1

```ruby
Product.rb:

attr_accessible: :unit_price_cents,:currency,:list_price_cents

monetize :unit_price_cents, with_model_currency: :unit_price_currency
monetize :list_price_cents, with_model_currency: :list_price_currency
```

```ruby
products db table structure:
unit_price_cents , unit_price_currency , list_price_cents, list_price_currency
```

any idea? Thanks

**Comment by kevin-jj** [comment]
I figured out that money-rails could not run in Rails3.2.21 but in Rails4.2

**Comment by semmons99** [comment]
Closed due to inactivity.
