### ISSUE TITLE
Allow t.monetize :column name to be bigint

### ISSUE THREAD

**Issue by dabobert** [RubyMoney/money-rails#349]
I'm on rails 4.2.1 and using postgres and i got unexpected behavior when the a value is out of range.  for instance before i had the following in my code

   create_table :hotels do |t|
          t.monetize :cost_of_flag, :limit => 8

and i then did

    h = Hotel.new
    h.cost_of_flag = 1234567890123445

but when costs of flag is larger than the default integer column, the value of cost_of_flag would be set to nil and my app would say cost_of_value is violating non null constraint (i forget the exact phrasing), even though i assigned it a non nil value.

in order to fix this i had to do 

    create_table :hotels do |t|
      t.integer :cost_of_flag_cents, limit: 8, default: 0, null: false
      t.string :cost_of_flag_currency, default: "USD", null: false

i understand this may be an edge case, but allowing the the the size of the column of the monetize column would fix it

**Comment by semmons99** [comment]
feel free to submit a pr

**Comment by semmons99** [comment]
Closed due to inactivity.

**Comment by mmahalwy** [comment]
@semmons99 i think this is valid still no?

**Comment by semmons99** [comment]
@mmahalwy sure, someone just needs to write the pr

**Comment by mmahalwy** [comment]
sorry, this works actually. with `amount: { limit: 8 }`

**Comment by antstorm** [comment]
linking this — #544
