### ISSUE TITLE
Model attribute writers should accept a hash like the one Money#to_json produces

### ISSUE THREAD

**Issue by zacstewart** [RubyMoney/money-rails#352]
The kind of interface I'd like to see is this:

```ruby
product.price = {
  'fractional' => '1077.0',
  'currency' => {
    'iso_code' => 'USD'
  }
}
product.price
# => #<Money cents:1077 currency:USD>
```

It looks like it wouldn't be too difficult to do that [here](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L142-L152) without changing the interface for assigning a `Numeric`.

I'm willing to issue the PR if it's likely to get merged. Seem useful to anyone else?

My rationale is that keeping the input and output formats the same is that it makes a simpler API. A client can modify what it `GET`s and `PUT` it back.

**Comment by semmons99** [comment]
This sounds great to me. I’d happily merge such a PR.

**Comment by semmons99** [comment]
Closed due to inactivity.
