### ISSUE TITLE
money_without_cents method does not round correctly

### ISSUE THREAD

**Issue by casiodk** [RubyMoney/money-rails#353]
ActionController::Base.new.view_context.money_without_cents(10.66, no_cents: true)
=> "10"

it should be rounded up to "11"

**Comment by antstorm** [comment]
@casiodk correct me if I'm wrong, but `no_cents: true` actually means shows price without cents

**Comment by antstorm** [comment]
Here's the line from the `money` gem — `Money.ca_dollar(599).format(:no_cents => true) #=> "$5"`

**Comment by semmons99** [comment]
Closed due to inactivity.

**Comment by casiodk** [comment]
But it doesnt make sense that 5.99 without cents is 5 it should be 6, or you should be able to set a rounding option

**Comment by antstorm** [comment]
@casiodk think of `no_cents` as truncation and don't use it when you're trying to round the value instead. However the need for truncation without rounding in the world of money is questionable, no doubts.

**Comment by casiodk** [comment]
Yes when dealing with money, it doesnt make sense, and its really annoying to have to do the correct rounding yourself. :)

**Comment by casiodk** [comment]
Otherwise a great gem, hope i don´t sound mad, i´m not ;)

**Comment by antstorm** [comment]
@casiodk there's always a compromise involved — some people will find `no_cents` performing rounding to be unintuitive :)

**Comment by casiodk** [comment]
<%= money_without_cents(Money.new(1066), round: true) %>

=> 11

**Comment by casiodk** [comment]
could this work then

**Comment by antstorm** [comment]
@casiodk sure, but do we need this when we can just:

```ruby
money_without_cents(Money.new(1066).round)
```

?
