### ISSUE TITLE
Money object in default currency equals 0 whereas any other currency does not

### ISSUE THREAD

**Issue by shifakhan** [RubyMoney/money-rails#355]
Setting default currency in money.rb
`config.default_currency = :aud`

In rails console,
    `Money.new(0) == 0                 #returns true`
    `Money.new(0, 'AUD') == 0      #returns true`
    `Money.new(0, 'JPY') == 0       #returns false`
Is there any specific reason for this behaviour ? Money object comparison with zero should probably throw an error. Otherwise all currencies should work the same way.

**Comment by semmons99** [comment]
I thought this was fixed in RubyMoney/money master branch (or even the latest release).

**Comment by semmons99** [comment]
Closed due to inactivity.
