### ISSUE TITLE
Money-rails seems incompatible with monetize gem - no longer supports parsing strings for money

### ISSUE THREAD

**Issue by Carpela** [RubyMoney/money-rails#360]
I'm getting a no method error when I try to use the 

    Monetize.parse(x)

    Monetize.parse_collection(x)

methods

Is there any way to get these working in tandem with the money-rails gem?

**Comment by AlexVPopov** [comment]
Hi @Carpela,

The `monetize` functionality has been extracted to the [monetize](https://github.com/RubyMoney/monetize) gem, as per the [readme](https://github.com/RubyMoney/money#rubymoney---money) of [money](https://github.com/RubyMoney/money).

Cheers,

**Comment by Carpela** [comment]
Hi Alex, 

I know. That's why I tried installing both. 

If I have money-rails installed alongside monetize then I get an error for Monetize.parse_collection

**Comment by Carpela** [comment]
Specifically, the Monetize.parse_collection method seems to not work. This is really, really useful when dealing with a load of somebody else's data from APIs..etc

**Comment by AlexVPopov** [comment]
@Carpela You are right. The problem seems to be, that the current version of `money-rails` uses `monetize` 1.1.0 and `parse_collection` was introduced in `1.2.0`. If you would like you could submit a PR for upgrading the version of `monetize` in `money-rails`.

**Comment by Carpela** [comment]
Ah... I see the issue. 
Money-rails is fixed on ~> 1.1.0 of monetize. 
1.1 never had the parse_collection method.

**Comment by Carpela** [comment]
Somebody had tried going to 1.3 already but wasn't passing Travis. 
Just tried just bumping to 1.2 with the same error. 
The issue appears to be with the mongoid builds.. Unfortuantely I'm not really a mongo person right now so I'm going to struggle to work a fix there...

**Comment by Carpela** [comment]
Error is this. Appears to be ignoring nil_priceable on mongo...
 1) Money demongoize returns nil if a nil value was stored
     Failure/Error: expect(nil_priceable.price).to be_nil
       expected: nil
            got: #<Money fractional:0 currency:EUR>
     # ./spec/mongoid/four_spec.rb:101:in `block (3 levels) in <top (required)>'
Finished in 2.52 seconds (files took 3.94 seconds to load)
225 examples, 1 failure
Failed examples:
rspec ./spec/mongoid/four_spec.rb:99 # Money demongoize returns nil if a nil value was stored

**Comment by nicknem** [comment]
So? What's the solution? I have the same issue.
