### ISSUE TITLE
money-rails doesn't work on sinatra app anymore

### ISSUE THREAD

**Issue by bertBruynooghe** [RubyMoney/money-rails#369]
We do have a sinatra app, currently using money-rails 0.12.0 and active record 4.1.6. 
Now we need to update active record to 4.2, which means we need to update money-rails too.

However, there are a number of rails dependencies introduced in the code so we can't pull this off...

**Comment by fotos** [comment]
@bertBruynooghe can you be more specific or provide an error message please? What is the problem exactly?

**Comment by bertBruynooghe** [comment]
Just can't start up the application anymore:

    ! Unable to load application: NameError: uninitialized constant Rails
    /Users/bruynooghebert/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/money-rails-1.4.1/lib/money-rails/hooks.rb:11:in `block in init': uninitialized constant Rails (NameError)

I also tried to hack around this by putting 
 
   module Rails
      module VERSION
        MAJOR = 6
      end
    end

if front of ```MoneyRails::Hooks.init```

but then I get:

    ! Unable to load application: ActiveRecord::ConnectionNotEstablished:     ActiveRecord::ConnectionNotEstablished
    /Users/bruynooghebert/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:109:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
            from /Users/bruynooghebert/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:105:in `connection_config'

**Comment by bertBruynooghe** [comment]
It might be fair not to provide support for this scenario anymore, but in that case rails should be moved to the regular dependencies iso. development dependencies in the gemspec.

**Comment by semmons99** [comment]
Please submit a PR.
