### ISSUE TITLE
there is no fractional in currency

### ISSUE THREAD

**Issue by poc7667** [RubyMoney/money-rails#370]
The answer supposed to be `32.398`, somehow, it didn't include fraction in the output.

# Output

    [5] pry(main)> Money.new(1, "USD").exchange_to("TWD")
    #<Money fractional:32 currency:TWD>
    [26] pry(main)> m1=Money.new(100.0134, 'USD')
    #<Money fractional:100 currency:USD>
    [27] pry(main)> m1=Money.new(100.321312, 'JPY')
    #< Money fractional:100 currency:JPY>
       
# My configuration

      config.register_currency = {
        :priority            => 1,
        :iso_code            => "TWD",
        :name                => "TWD",
        :symbol              => "NT$ ",
        :symbol_first        => true,
        :subunit         => "Cent",
        :subunit_to_unit => 100,
        :thousands_separator => ",",
        :decimal_mark        => "."
      }

      config.register_currency = {
        :priority            => 1,
        :iso_code            => "USD",
        :name                => "USD",
        :symbol              => "$ ",
        :symbol_first        => true,
        :subunit         => "Cent",
        :subunit_to_unit => 100,
        :thousands_separator => ",",
        :decimal_mark        => "."
      }

      config.add_rate "TWD", "USD", 0.03086610284585468
      config.add_rate "USD", "TWD", 32.398

**Comment by takiy33** [comment]
This is same https://github.com/RubyMoney/money/issues/561.

**Comment by semmons99** [comment]
dup, closed. Please submit a PR.
