### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by stanley90** [RubyMoney/money-rails#379]
Hi

When can I expect new release of money-rails? I'm trying to use https://github.com/spk/money-open-exchange-rates version 0.4.0 because of a new feature, which depends on `monetize 1.3`, whereas latest `money-rails 1.4.1` depends on `monetize 1.1` (but master has already `1.3`).

Thanks

**Comment by semmons99** [comment]
soon, waiting for the repo to settle down. For now, just point to a GitHub SHA if you need something.
