### ISSUE TITLE
Too many issues

### ISSUE THREAD

**Issue by vemv** [RubyMoney/money-rails#381]
There is a number of abandoned or low-quality issues, which makes opening new issues cumbersome (I have to read a lot of noise before determining my issue is not duplicate) and hurts the project overall health/reputation (past a issue threshold, ones starts seeing gems as unmaintained).

Please mercilessly close a few of those. :)

**Comment by semmons99** [comment]
Done! Thanks for reminding me. I'm usually pretty brutal about it.
