### ISSUE TITLE
uninitialized constant Money::RatesStore

### ISSUE THREAD

**Issue by ZuevEvgenii** [RubyMoney/money-rails#383]
money-rails gem version 1.4.1
money gem version 6.5.1

`@store = Money::RatesStore::Memory.new`

`NameError: uninitialized constant Money::RatesStore`

**Comment by paulodiniz** [comment]
I think upgrading your gem to 6.6.0 versions of the money gem will work. As said on https://github.com/RubyMoney/money/issues/568 , the 6.5 versions do not have that class. 

Upgrading your gemfile will work :smiley:

**Comment by antstorm** [comment]
Closing, issue is solved
