### ISSUE TITLE
Assigning to nil now returns zero-valued money object

### ISSUE THREAD

**Issue by joekur** [RubyMoney/money-rails#384]
Just switched to latest master from 1.4.1. Found I had a test failure and tracked it down to a change in behavior when setting a monetized column to nil. It now returns a 0 value money object.

Before (1.4.1):

``` ruby
MyModel.new(price: nil).price # => nil
```

Master:

``` ruby
MyModel.new(price: nil).price # => #<Money fractional:0 currency:USD>
```

Was this intentional?

**Comment by joekur** [comment]
I see this is caused by a difference in `nil.to_money`, which used to be an undefined method but now returns 0 money.

**Comment by joekur** [comment]
So the monetize gem changed in 1.3.0: https://github.com/RubyMoney/monetize/blob/master/CHANGELOG.md#130

Related issue: https://github.com/RubyMoney/monetize/issues/47

I suppose this was indeed intended in Monetize. It was a bit of a breaking change (at least in my app) and took a little while to track down that it was due to a change in a dependency.

Also worth noting that this behavior is not the case if you are using `allow_nil: true`, in which case it will happily leave the monetized column as nil.

**Comment by antstorm** [comment]
@joekur that's a good point. It certainly doesn't feel right to be using `allow_nil: true` in order to prevent this.

**Comment by joekur** [comment]
I guess personally I would be fine with the behavior that we had before: setting to nil never defaults the value to 0. Do you agree? I'd be happy to work on a PR if so.

**Comment by antstorm** [comment]
@joekur sorry for no reply, yes it definitely feels wrong — setting monetized attribute to nil should reset amount & currency. I'd be happy to review and merge a PR for this one.

**Comment by joekur** [comment]
I think there's a scenario if you have more than one monetized field sharing a currency column. We would not want the currency field to be overwritten in that case. In fact I dusted off my fork and remembered I had made a branch to fix this, which is broken whether `allow_nil` is true or not.

I imagine it's possible to handle resetting the currency field if it's a shared currency column only if all dependent money fields are nil, but that gets a little complicated.

**Comment by mstate** [comment]
I had the reverse situation where I wanted allow_nil due to nil data provided on input that I didn't want to translate to 0 cents in the database (too many fields and places to make the change).  But, for calculations, I didn't want to have to force a to_money on every attribute read.  I added the following to a config initializer to make nil cents values in the database be read as 0.to_money.
`
# config/initializers/money-rails-nil-to-zero.rb
# Force nil values to be zero money on read.

module MoneyRails
  module ActiveRecord
    module Monetizable
      alias_method :original_read_monetized, :read_monetized

      def read_monetized(name, subunit_name, *args)
        original_amount = original_read_monetized(name, subunit_name, *args)
        if original_amount
          return original_amount
        else
          return 0.to_money(public_send("currency_for_#{name}"))
        end
      end
    end
  end
end
`

Thought someone else might find it helpful.
