### ISSUE TITLE
MoneyRails helpers access in Minitest

### ISSUE THREAD

**Issue by ZombieHarvester** [RubyMoney/money-rails#386]
Hi there, how i can get access to MoneyRails helpers (e.g. humanized_money_with_symbol) from Minitest? Thanks

**Comment by popup-user** [comment]
You might try ```ActionView::Base.new.humanized_money_with_symbol. ```
@antstorm figured it out for me here: https://github.com/RubyMoney/money-rails/issues/392

**Comment by antstorm** [comment]
@ZombieHarvester @popup-user it seems like there are some other ways of doing that —

- Use `ApplicationController.helpers.money_without_cents`
- Include `MoneyRails::ActionViewExtensions` into your model and call the method directly

**Comment by popup-user** [comment]
ah, nice! Much better.

**Comment by ZombieHarvester** [comment]
@popup-user @antstorm Thanks!

**Comment by ZombieHarvester** [comment]
`include MoneyRails::ActionViewExtension` provides access to MoneyRails helpers outside ActionView

`ActionView::Base.new.humanized_money_with_symbol` works as well, but is a bit heavier
