### ISSUE TITLE
does using :price as db-column_name name create issue?

### ISSUE THREAD

**Issue by marczking** [RubyMoney/money-rails#387]
I wanted to use `price` as column_name.

When I then ran `monetize :price` in my model my app didn't load or hung up. Not sure what went wrong, in the end I had to restart my pc.

Does my column_name have to differ from "price". Or is this irrelevant?

**Comment by antstorm** [comment]
@marczking what error did you get?

Yeah, basically the idea is that you'd use `price_cents` as the column name and then `monetize` it, getting `price` as the attribute.

**Comment by marczking** [comment]
I didn't really get an error, it just gave back on what line it was having problems and didn't continue...

So I'll just use "_cents" at the end and be fine :smile:
