### ISSUE TITLE
Can't use latest version of money

### ISSUE THREAD

**Issue by bsgreenb** [RubyMoney/money-rails#389]
The gemspec for rails-money requires money v.6.5.  to use the new `from_amount` method i need to upgrade to 6.6  what do I do?

**Comment by semmons99** [comment]
Submit a PR.

**Comment by antstorm** [comment]
@bsgreenb since money-rails depends on money `~> 6.5` you can add money `6.6` into your app's Gemfile and money-rails should pick it up.
