### ISSUE TITLE
Can I use the money_without_cents helper in the model?

### ISSUE THREAD

**Issue by popup-user** [RubyMoney/money-rails#392]
Hi, I'd like to use the "money_without_cents" helper method in a model, but I can't seem to figure out the syntax. I've tried to access the helper method via:

ActionView::Helpers::MoneyRails
ActionView::Base::MoneyRails.money_without_cents
ActionView::Base.money_without_cents
and I even tried:
ActionController::Base.helpers.MoneyRails

These don't work. Does someone know the answer? 
Thanks

**Comment by antstorm** [comment]
Try calling it directly on `MoneyRails::ActionViewExtension`…

**Comment by popup-user** [comment]
Thanks for the idea @antstorm , but alas, it failed with:
NoMethodError: undefined method `money_without_cents' for MoneyRails::ActionViewExtension:Module

**Comment by antstorm** [comment]
@popup-user sorry for that, got to the console and figured it out. So the `MoneyRails::ActionViewExtension` is included into `ActionView::Base` on load. Meaning that `ActionView::Base.new.money_without_cents` will give you the method you're looking for.

**Comment by popup-user** [comment]
@antstorm Creating a new instance of ActionView::Base doesn't seem exactly... efficient, but I guess it works, at least! Thank you!
