### ISSUE TITLE
<Money>.to_json returns a huge hash

### ISSUE THREAD

**Issue by joekur** [RubyMoney/money-rails#393]
I'm thinking this belongs here instead of the money gem since `to_json` / `as_json` is a rails (ActiveSupport) related method.

By default `as_json` serializes all instance variables, so both `currency` and `bank` keys are themselves huge hashes.

I think a more sane default would be fractional + currency? Maybe symbol too. Happy to put up a pull if we can agree on the keys.

**Comment by joekur** [comment]
Looks related to this pull: https://github.com/RubyMoney/money-rails/pull/391

**Comment by antstorm** [comment]
Sorry, accidentally closed it…

I'm not sure if there's a good way to serialize Money object so that everyone's happy. In case of a front-end API you might wanna return formatted string, for backend stuff — amount/currency?, and so on.

Plus this happens only when you try to serialize the Money object directly…

Btw, mentioned PR doesn't look to be related to this.

**Comment by blairanderson** [comment]
For anyone that wants a quick fix, you can overwrite as_json inside money and things will work as you want. 

I used:

```ruby
class Money
  def as_json
    self.to_f
  end
end
```

I think a future API could be successful if users could provide a serialization proc/class when calling the `monetize` macro.

**Comment by antstorm** [comment]
Would it make sense to have this method return `{ fractional: fractional, currency: currency.iso_code }` by default?

**Comment by hudakh** [comment]
Any update on this?

**Comment by FunkyloverOne** [comment]
If you're already using active_model_serializers, you can simply create custom serializer for Money objects, here's mine for example:
```ruby
  class MoneySerializer < ApplicationSerializer
    attributes :cents, :amount, :currency_iso, :symbol, :formatted_string

    def cents
      object.cents
    end

    def amount
      object.amount.to_f
    end

    def currency_iso
      object.currency.iso_code
    end

    def symbol
      object.currency.symbol
    end

    def formatted_string
      object.format
    end
  end
```

And then inside other serializers use `has_one` method for money fields, like this:
```ruby
  class ProductSerializer < ApplicationSerializer
    attributes :id, :title, :description            
    has_one :price
  end
```

**Comment by antstorm** [comment]
In case people still wanna stick to `as_json`, here's a PR — #568
