### ISSUE TITLE
Using PostgreSQL money column

### ISSUE THREAD

**Issue by nunof** [RubyMoney/money-rails#396]
Hello,

I'm trying to use money-rails with PostgreSQL money column but I can't get it to show decimals (cents). What am I doing wrong?

schema.rb:
t.money "money",                 scale: 2,     null: false

structure.sql:
money money NOT NULL,

Rails model:
monetize :money

humanized_money_with_symbol(Model.money) shows proper formatting (with € symbol in my case) but I can never see the fractional part...

Thanks in advance

**Comment by simonoff** [comment]
You don't need to use money type in rails. It will not work. Because all what is needed is an integer. And money-rails store CENTS into database, not float.

**Comment by nunof** [comment]
Thanks for the quick reply. I guess I will risk an offtopic question. Since I'm using PGSQL and it has a money column type, can I use it in Rails, even if in that case I should not use money-rails?

If so, I guess I will have something like a BigDecimal in ruby and go from there right?

Thanks

**Comment by simonoff** [comment]
```
Notice for Rails >= 4.2 and PG adapter

Due to the addition of the money column type for PostgreSQL in Rails 4.2, you will need to use add_monetize instead of add_money column. If you're adding the column within a create_table block, use t.monetize, and use remove_monetize to remove the column.
```

**Comment by amartinezg** [comment]
Hi @nunof 

I'm facing something similar to your case but as @simonoff mentioned, money column is added by that new helper, which means that will return to you a BigDecimal in your rails application instead Money object.

`helper.humanized_money_with_symbol` should show the fractional part regardless type of column in this case, the other option is you transform BigDecimal to a Money Object `Model.money.to_money` an after that you can call `.format` or `.cents`, whatever you want from `money` gem. 

Tell me if you find any way to get money object directly.

Thanks

**Comment by amartinezg** [comment]
Hi @nunof 

I'm sorry for my last answer, I've realized that in the migration I put `t.money` instead of `t.monetize` as @simonoff mentioned and that was the reason a column with money type was created.

You should use gem migration `add_monetize` or `t.monetize` in order gem automatically create both columns `money_cents` and `money_currency`, in that way you can get the proper money object.

I'm afraid even newer postgresql version include money type, gem keeps using same format, for `_cents` column always will be stored as integer.

Hope it helps.

**Comment by nunof** [comment]
Hello,

Sorry for the late reply. I've avoided the problem altogether since I'm
using pgsql money type which is perfectly supported by recent ROR.

Cheers

/nunof while mobile

**Comment by antstorm** [comment]
@naqib83 if you want to set the value in dollars (not in cents) then you should use `transaction_price` param
