### ISSUE TITLE
Get only cents part from money

### ISSUE THREAD

**Issue by iBublik** [RubyMoney/money-rails#397]
Is there any built-in way to get only cents part of the money? Thanks in advance :)

**Comment by amartinezg** [comment]
Hi @iBublik 

You have a method called `.cents` for each Money Object.

`# 10.00 USD`
`money = Money.new(1000, "USD")`
`money.cents     #=> 1000`
`money.currency  #=> Currency.new("USD")`

See: https://github.com/Rubymoney/money#usage

Hope it helps

Cheers

**Comment by iBublik** [comment]
Hi @amartinezg. Thanks for your reply. I think I've provided too little info so you misunderstood me. What I wantis to get 50 (excactly cents without dollars) from following example:
```ruby
money = Money.new(1050, 'USD')
humanized_money(money) #=> $10.50
# following method probably have another name or doesn't' exist, it's here just to explain what I want
only_cents_without_dollars(money) #=> 50
```
Currently I'm using `subunit_to_unit` to get this value, but maybe there's pretty built-in way.

**Comment by antstorm** [comment]
@iBublik I would suggest raising this in [money repo](https://github.com/RubyMoney/money). Right now it's being done like this:

```ruby
unit, subunit = fractional.abs.divmod(currency.subunit_to_unit)
```
