### ISSUE TITLE
Upgrade to money 6.6

### ISSUE THREAD

**Issue by joelmichael** [RubyMoney/money-rails#398]
Hey guys,

We are using the money-rails gem and realized that it is still locked to version 6.5 of the money gem. However this is causing us some issues with Canadian currency that have been fixed by the money gem in 6.6.

Can you guys release an update to money-rails that has money 6.6?

Thanks

**Comment by semmons99** [comment]
Sumita PR and we should be able to do that

**Comment by antstorm** [comment]
Already on `6.7`, closing this
