### ISSUE TITLE
Currencies

### ISSUE THREAD

**Issue by BigChief45** [RubyMoney/money-rails#404]
Hi

I am trying to implement money-rails but I do not see the list of available currencies for use? I get a migration error if I just try using my currency's name.

Would appreciate some help.

**Comment by semmons99** [comment]
Check the money gem, or use irb to inspect Money::Currency

- shane

**Comment by ricardopacheco** [comment]
@BigChief45 open rails console and input => Money::Currency.load_currencies

**Comment by antstorm** [comment]
Closing this one, since it's not related to `money-rails` and @ricardopacheco's solution should work
