### ISSUE TITLE
Wrong implicit conversion before saving model

### ISSUE THREAD

**Issue by Nghi93** [RubyMoney/money-rails#408]
Hi,

I am using the default currency USD.
When I assign a money object to a model and save this model I get the wrong value object.
For example: 
u = User.new
u.balance = Money.new(1000, 'EUR')
u.save
u.balance 
=> Money.new(1000, 'USD')

The currency has just changed, but not the value.
To mention is that I am using a custom exchange, but #exchange_to works fine.

I think it's a weird behavior that just the currency is changed but not also the value.
Am i supposted to convert it on my own before save?

**Comment by ben-av** [comment]
For me it changes back to USD even before saving. 
Any simple way to handle this?

**Comment by Nghi93** [comment]
Could you give an example?

**Comment by ben-av** [comment]
```
class CashOrder < ActiveRecord::Base
  monetize :money_col_cents
end


order.money_col = Money.new(100, 'EUR')
<Money fractional:100 currency:EUR>
order.money_col
#<Money fractional:100 currency:USD>
```

**Comment by Nghi93** [comment]
You can set default currency to eur or try to call
order.money_cal_cents_before_type_cast

**Comment by barnett** [comment]
@Nghi93 but I believe currency should be able to be dynamic to whatever currency you want to set with (without needing to change the default). We are having the same issue, as demonstrated in #432

**Comment by antstorm** [comment]
Opened a PR which should fix the issue ^

@Nghi93 and @ben-av to make sure the fix works in your cases could you give me your `monetize` definitions and DB columns used?

**Comment by ben-av** [comment]
Hi @antstorm,
I used the regular 
```
add_money :orders, :money_col
```

**Comment by antstorm** [comment]
@ben-av right, that means that you have a currency column and my fix should work. Can you please try it out?

```ruby
gem 'money-rails', github: 'antstorm/money-rails', branch: fix-inferred-currency-column-updating'
```

**Comment by ben-av** [comment]
@antstorm 
Works great, thanks!
