### ISSUE TITLE
"humanized_money" doesn't honor decimal mark and thousands separator of currency

### ISSUE THREAD

**Issue by manuelmeurer** [RubyMoney/money-rails#410]
```ruby
m = Money.new(123456, 'EUR')
m.currency.decimal_mark # ","
m.currency.thousands_separator # "."

include MoneyRails::ActionViewExtension
humanized_money_with_symbol m # "€1,234.56"
```

I would have expected `€1.234,56`, i.e. with the decimal mark and thousands separator according to the currency config.

**Comment by antstorm** [comment]
I'll take a closer look later, but it feels like the `humanized_money_with_symbol` is not using the modified currency instance…

**Comment by manuelmeurer** [comment]
I took a stab at it: #411

**Comment by manuelmeurer** [comment]
@antstorm Could you have a look at my PR if you have a minute? Thanks!

**Comment by antstorm** [comment]
@manuelmeurer sure thing!
