### ISSUE TITLE
Upgrade to 1.6.0 breaks some logic

### ISSUE THREAD

**Issue by vanboom** [RubyMoney/money-rails#412]
I have some specs and model logic that compares a money object with zero... e.g.

```ruby
if invoice.total > 0
  ...
end
```
On 1.4.1 this logic worked ok, I guess the Money object was being automatically promoted to a float or int? 

After upgrading to 1.6.0, this logic fails with an exception: 
```
ArgumentError:  comparison of Money with 0 failed
```
Is this the desired behavior?  Or potentially a bug?

**Comment by cyruscavalcante** [comment]
+1

**Comment by antstorm** [comment]
https://github.com/RubyMoney/money/pull/607 seem to fix this issues

**Comment by SylarRuby** [comment]
It's a pain but do this:

```
if invoice.total > 0.to_money
  ...
end

```

Which money comparing money totally make sense.

**Comment by antstorm** [comment]
@SylarRuby you can compare amount column directly, which is better — `if invoice.total_cents > 0`

**Comment by SylarRuby** [comment]
@anthonator guess it would be the same? `if invoice.total_cents > 0.to_money` This works for me so I'm not sure if there is a better way of doing it. Basically you are saying if 1.00 is greater than 0.00.

**Comment by antstorm** [comment]
@SylarRuby I mean you don't need to cast `0` to money object, since `total_cents` is an Fixnum (unlike `total`, which is an instance of `Money`).

**Comment by SylarRuby** [comment]
Nice one ;)
