### ISSUE TITLE
Change cents to value.

### ISSUE THREAD

**Issue by nsantiago2719** [RubyMoney/money-rails#415]
Are there any way to change the default field cents to value? Im having a problem here because when I input  like Philippine Peso 120 it shows  Php 1.20 in the view. I have found out that every time that I save a price it will save it as cents that's why I get 1.20, but what I want to show is PHP 120 not 1.2 .

**Comment by antstorm** [comment]
@nsantiago2719 `money-rails` and `money` are both using Fixnum to represent values in cents. So in your case you need assign value of 12000 to get PHP 120.00.

**Comment by nsantiago2719** [comment]
Are there other work around except from assigning the value to 12000?

**Comment by antstorm** [comment]
@nsantiago2719 you can also assign 120 directly to your monetized attribute instead of the cents field, or you can assign it a `Money.from_amount(120, 'PHP')`

**Comment by nsantiago2719** [comment]
Ok, got it.
