### ISSUE TITLE
currency_model set after results in incorrect subunit

### ISSUE THREAD

**Issue by naps62** [RubyMoney/money-rails#416]
I have a model with this:

```
monetize :value_subunit, as: :value, with_model_currency: :currency
```

BTC has a unit_to_subunit value of 100000000, but this is currently depending on me settings the correct currency before the value.
In Ruby, at hashes are ordered (not as a feature, but as an implementation detail), so the arguments are assigned to a model in the same order that they are declared

In other words, this happens:

```ruby
# passing in the currency before the value works properly
correct_model = ECard.new(currency: 'BTC', value: 1)

correct_model.value_subunit
# => 100000000
correct_model.value.to_f
# => 100.0


# if the value happens to be before the currency, the default subunit is used
incorrect_model = ECard.new(value: 1, currency: 'BTC')

incorrect_model.value_subunit
# => 100
incorrect_model.value.to_f
# => 1.0e-06
```

It seems the while Money is calculating the subunit, the currency is not set yet, so it falls back to the default one, and considers a subunit of 100 (which for BTC is wrong). The currency is then changed to BTC, but the value_subunit is not updated to reflect this

**Comment by antstorm** [comment]
@naps62 you can avoid this by setting `value_subunit` instead of `value` when initializing `ECard`. I know this does sound confusing, but keep in mind that `value` is a cached instance of `Money`, it's not just a numeric value.

**Comment by naps62** [comment]
@antstorm thanks for the answer

but by doing that I would have to use `value_subunit: 100` instead of `value: 1` right? (assuming the value is 1.00$)

that doesn't work for my case either because the subunit depends on the currency (I use not only BTC, but also Gold, Silver, and a couple of custom currencies)

So that solution still requires me to add some logic to find the correct value


One question, though. If the value is an instance of Money, could I do something like this?

```
ECard.new(value: Money.new(value, currency))
```

The above would work for me I believe, and looks much better

**Comment by antstorm** [comment]
Yes, absolutely, you can use an instance of `Money` as a value

**Comment by naps62** [comment]
@antstorm I went ahead and tried that in the meantime. It doesn't seem to work properly either

Following the example in the original post:

```
# correct value
ECard.new(currency: 'BTC', value: 1).value_subunit
# => 100000000

# your suggestion
ECard.new(value: Money.new(1, 'BTC')).value_subunit
# => 1
```

I tried appending the `currency` parameter as well, both before and after, but it also doesn't work with your suggestion
It also seems to do even worse for floating point values

**Comment by antstorm** [comment]
@naps62 so the trick is that by passing a number to `value` it treats it like a unit, while `Money.new` treats the provided value like a subunit, causing this confusion.

**Comment by antstorm** [comment]
@naps62 if you still want to use units you can use `Money.from_amount` instead of `Money.new`, it acts exactly the same, but accepts units instead of subunit:

```
>> Money.new(1, 'BTC')
=> #<Money fractional:1 currency:BTC>
>> Money.from_amount(1, 'BTC')
=> #<Money fractional:100000000 currency:BTC>
```

**Comment by naps62** [comment]
@antstorm Oh, that's right.
I've actually used `from_amount` on a previous project, but I didn't remember about it for some reason.

Thanks for the support, and keep up the good work!
