### ISSUE TITLE
Allow `symbol_first` to be set in `default_format`

### ISSUE THREAD

**Issue by paulmenzel** [RubyMoney/money-rails#417]
In Germany, the € is displayed after the price (10 €), so it’d be great to be able to override the default by RubyMoney to display it before the value.

**Comment by antstorm** [comment]
Is that country specific? Or currency specific?

Either way will be happy to merge that change in.

**Comment by thomasnaude** [comment]
+1

**Comment by sivagollapalli** [comment]
@antstorm  Looks like this issue has been fixed. I have seen related https://github.com/RubyMoney/money-rails/blob/master/spec/configuration_spec.rb#L75 spec . Let me know if I misunderstood .

**Comment by antstorm** [comment]
@sivagollapalli good point! @paulmenzel can you please check if that behaves the way you wanted?

**Comment by r-obeen** [comment]
Hello,
Can't find a way to put the symbol after the price... is it possible to do so ?
Ex : `10,00 €` instead of `€10,00`

**Comment by antstorm** [comment]
@r-obeen try `Money.new(10_00, 'EUR').format('%n %u')`. I don't think we have an option to configure this as a default behaviour, but happy to accept a PR

**Comment by r-obeen** [comment]
> @r-obeen try `Money.new(10_00, 'EUR').format('%n %u')`. I don't think we have an option to configure this as a default behaviour, but happy to accept a PR

Yep there is an option for that. See my previous answer 👍🏾

**Comment by antstorm** [comment]
@r-obeen happy to accept a PR updating docs on this 👍
