### ISSUE TITLE
Wrong currency used in model initialization if passed from form

### ISSUE THREAD

**Issue by tangopium** [RubyMoney/money-rails#421]
There is a problem if the currency is passed by a form:

```
 = f.input :price
 = f.input :price_currency, collection: currency_list
```

If the parameters are assigned to the model, money-rails in the background first initiates a Money object with the default currency (in general USD) and later assigns the currency. This is a problem if the "subunit_to_unit" (defined in the money gem) of both currencies is different.

If you try for example to assign 1,000 CLP (subunit_to_unit: 1) money-rails instantiates the object with USD (subunit_to_unit: 100), hence the value is multiplied by 100. The result is that I have 100,000 CLP assigned.

I suppose the problem could be solved by considering the subunit_to_unit when changing the currency.

**Comment by antstorm** [comment]
@tangopium care to open a PR for this one?
