### ISSUE TITLE
Pennies Not Saving

### ISSUE THREAD

**Issue by SylarRuby** [RubyMoney/money-rails#426]
Pardon my stupidity but I cannot save a pennies. I'm using Rails 4 and PG. I have a monetize column and I want to save: `total_pennies = 3.50`. Only `3` gets saved. Why? Now, the value of `total_pennies` is `0.03`

**Comment by antstorm** [comment]
@SylarRuby I guess you figured it out — the amount column is in pennies, not pounds.

**Comment by SylarRuby** [comment]
Lol yes ;)
