### ISSUE TITLE
Work with unit currency instead of cents

### ISSUE THREAD

**Issue by MrPhantomT** [RubyMoney/money-rails#429]
It is gonna be great if we will have possibility work with unit currency instead of cents, alongside with current implementation.
Money gem has `from_amount` method, which provided possibility to instantiate Money object from unit currency.
It can be useful for working with big money, when cents not using at all.
Thanks.

**Comment by antstorm** [comment]
@MrPhantomT I think whenever you're dealing with money you always want cents, because you never know what's waiting for you — currency conversion, for example, absolutely needs cents.

If that's definitely what you need then you can always create some helper methods that will abstract cents away.

**Comment by antstorm** [comment]
@MrPhantomT I might have misunderstood your request. Can you give me an example of what you mean?

**Comment by MrPhantomT** [comment]
@antstorm Sorry for the delay in replying. I agree with your opinion. The case with which i encountered was due legacy code, and I chose wrong way to solve it. I'll close this pull request.
Thank for your help.

**Comment by antstorm** [comment]
@MrPhantomT no worries, I'm glad you've resolved it.
