### ISSUE TITLE
*_currency fields not updating

### ISSUE THREAD

**Issue by arcwhite** [RubyMoney/money-rails#432]
My expectation based on the documentation is that per-attribute currency fields will update when the corresponding amount field is updated. For example:

```
class Product < ActiveRecord::Base
  monetize :amount_cents
end

p = Product.new(amount: 100)
# => #<Product amount_cents: 100, amount_currency: 'USD'>

p.amount = p.amount.exchange_to('AUD')
# => #<Product amount_cents: 65, amount_currency: 'AUD'>
```

What I see in practice is that amount_cents is updated, but amount_currency is not.
Looking at https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb I can see code to update the instance_currency field on the model, but nothing that would update (say) "#{name}#{MoneyRails::Configuration.currency_column[:postfix]}"

Are my expectations valid, or is it my responsibility to update the currency field manually when I do an exchange?

**Comment by barnett** [comment]
Same problem as https://github.com/RubyMoney/money-rails/issues/408

**Comment by antstorm** [comment]
@arcwhite thanks for pointing out, I'm surprised it was left behind. I've opened a PR for this. 

P.S. Before it's merged and released you can explicitly specify `with_model_currency: :amount_currency`, which should do the trick.
