### ISSUE TITLE
Change money currency attribute

### ISSUE THREAD

**Issue by crilam** [RubyMoney/money-rails#436]
Hi, is there a way to update the currency attribute from an Money Instance.

Maybe...
m= Money.new(100, 'USD')
m.currency = Money::Currency.new("EUR")

Or something like.

m.update_attribute (currency: Money::Currency.new("EUR"))

Or
m.change_currency("EUR")

**Comment by crilam** [comment]
I forget to say that I can't change currency in a mongoid base application.

**Comment by antstorm** [comment]
@crilam are you using a DB field for currency? Or is it a virtual attribute?

**Comment by crilam** [comment]
@antstorm, i tried both ways with in a mongoDB, but i could not find the way to pass the parameter :with_currency or with_model_currency in the model.

**Comment by antstorm** [comment]
@crilam sorry, I think I misunderstood your question in the first place. So what you can do is:

```
m = Money.new(100, 'USD')
m.currency_as_string = 'EUR'
```

And that should work as expected

**Comment by crilam** [comment]
@antstorm, that worked well in the rails console, but when i try to make an virtual attribute i can`t update the currency.

My model looks like this
---------------------------------------------
class Contract
 # == MongoDB
  include Mongoid::Document
  include Mongoid::Timestamps
  include GlobalID::Identification
    
  belongs_to :property

  # == Atributos
  field :value,       type: Money,    default: 0.0

  def currency
    self.value.currency
  end
  
  def currency=(val)
    self.value.currency_as_string = val
  end
end

**Comment by antstorm** [comment]
@crilam what you're probably doing wrong is applying changes to `Contract.last` on every call, which gets a different object every time, so you're not modifying an object. Try this instead:

```ruby
contract = Contract.last
contract.value.currency_as_string = "EUR"
contract.save
contract.reload
contract.value.currency_as_string
```

**Comment by crilam** [comment]
@antstorm that isn´t working

[6] pry(main)> contract = Contract.last
=> #<Contract _id: 5734e14dc4b8db4608cce08d, created_at: 2016-05-12 20:02:21 UTC, updated_at: 
.....
[7] pry(main)> contract.value.currency_as_string = "EUR"
=> "EUR"
[8] pry(main)> contract.save
=> true
[9] pry(main)> contract.reload
[10] pry(main)> contract.value.currency_as_string
=> "BYR"

# What Worked is .... Redefine currency setters and getter.

class Contract
  include Mongoid::Document
  include Mongoid::Timestamps
  include GlobalID::Identification
  
  field :value,       type: Money,    default: 0.0

  def currency
    self.try(:value).try(:currency_as_string)
  end

  def currency=(val)
    self.value = Money.new(self.value.fractional, val)
  end
end

**Comment by antstorm** [comment]
@crilam got it, will take a closer look

**Comment by antstorm** [comment]
@crilam sorry for a delay, finally got to check this issue. So it seems like this is an issue and any changes to `Money` object are ignored. Here's a workaround:

```ruby
contract = Contract.last
value = contract.value
value.currency_as_string = "EUR"
contract.value = value
contract.save
contract.reload
contract.value.currency_as_string
```

I'll also take a look at fixing the gem to allow changing the currency directly on the object.

**Comment by antstorm** [comment]
@crilam to comment further this is what I found in the source — "Money is a value object and should be treated as immutable". Meaning that you should always be initializing a new `Money` object whenever you need to change it.

Example:

```ruby
contract = Contract.last
contract.value = Money.new(contract.value, 'EUR')
contract.save
```
