### ISSUE TITLE
monetize function doesn't define proper methods

### ISSUE THREAD

**Issue by infertux** [RubyMoney/money-rails#438]
When I do `monetize :my_attribute_cents`, it doesn't define `my_attribute` but `my_attribute_cents_money` instead. It happens consistently on different models and attribute names. I'm using Rails 5 so that might be why?

- `money` version 6.7.1
- `money-rails` version 1.6.1

**Comment by antstorm** [comment]
@infertux it looks like it falls back to the last resort case. What are your `amount_column` settings in the configuration file? Feels like it might be missing the `postfix: '_cents'` option.

**Comment by infertux** [comment]
Spot on! I've set the default currency to GBP and was storing it as `attribute_cents` in the DB to stay generic but Money is too smart and was expecting `attribute_pennies`. Adding this second line fixed it:

```
  config.default_currency = :gbp
  config.amount_column[:postfix] = '_cents'
```

**Comment by antstorm** [comment]
@infertux yeah, glad you've solved it. Not sure if the whole localization of postfix is a good thing, might be quite confusing, but at least there's a way to override it.

**Comment by sevos** [comment]
postfix localization does not make sense. which postfix would be used in case when

- default currency is set to GBP
- amount_currency value in given row is USD

in current implementation it would be `_pennies` but it does not make sense anyway. do we localize for every language? amount_grosze for PLN?
