### ISSUE TITLE
Missing rounding_mode in generated initializer

### ISSUE THREAD

**Issue by mmichaa** [RubyMoney/money-rails#440]
Hi, folks. I used the money and money-rails gem the first time. It's really awesome! Thanks for that! 👍  Today I have noticed, that there is a round_mode parameter in the README file: https://github.com/RubyMoney/money-rails/tree/v1.6.1#configuration-parameters But this section is missing in the template for the generator: https://github.com/RubyMoney/money-rails/blob/v1.6.1/lib/generators/templates/money.rb Maybe you want to fix that 😅  Greetings, Michael.

**Comment by antstorm** [comment]
@mmichaa good catch, thank you!

**Comment by antstorm** [comment]
@mmichaa I've added it to the template, thanks for noticing it. Btw, you're always welcome to submit PR for these things :)
