### ISSUE TITLE
Currency save order

### ISSUE THREAD

**Issue by geekerzp** [RubyMoney/money-rails#445]
Hi, this is my model
```ruby
class Product::Price < ApplicationRecord
  monetize :price_cents,
           with_model_currency: :currency, numericality: { greater_than: 0 }
end
```
I run the following code and I got correct price:
<img width="628" alt="2016-06-18 9 52 22" src="https://cloud.githubusercontent.com/assets/2854886/16171340/fffe2eb2-359e-11e6-9905-dcb5178d095f.png">

But when I run the code in different order:
<img width="633" alt="2016-06-18 9 55 13" src="https://cloud.githubusercontent.com/assets/2854886/16171356/5ee6a79c-359f-11e6-8dc0-6350d53a8f74.png">

The price is wrong which should be "¥12"

**Comment by antstorm** [comment]
@geekerzp there are couple of things that you might be doing wrong:

1. `price` is a virtual attribute, you should be setting `price_cents` instead, which shouldn't cause any problems. If you want to set `price` directly, use `Money` instance as value
2. ISO 4217 states that JPY doesn't have a subunit, so giving it a float as value causes unpredictable behaviour

Can you also specify the version of gem that you're using? I'm not seeing the same behaviour with the latest one.

**Comment by geekerzp** [comment]
This is my gem versions.
<img width="342" alt="2016-06-20 9 41 00" src="https://cloud.githubusercontent.com/assets/2854886/16181277/4b87b060-36cb-11e6-9848-6afe86922cb8.png">

**Comment by geekerzp** [comment]
I have to make the users input their price number and price currency directly,  and the users may be in different countries.
So I can't use `p.price = Money.new`, as the users don't know their price number in cents.
Below is my view:
```ruby
<%= f.text_field, :price %>
<%= f.select :currency, currency_select_options %> 
```
Very appreciate! @antstorm

**Comment by antstorm** [comment]
@geekerzp it seems that this issues is fixed in `master`, I'll release `1.6.2`. Meanwhile, can you please try the same code using latest `master`?

**Comment by antstorm** [comment]
New version is now live, can you please confirm that it resolves your issue?

**Comment by geekerzp** [comment]
Confirmed it is fixed, thanks @antstorm
