### ISSUE TITLE
Wrong Decimal Round with some prices

### ISSUE THREAD

**Issue by S200124** [RubyMoney/money-rails#452]
Hi to all.
I have a round problem with this gem...I tried a lot of solutions but none of them worked.
Here's an example:
In Italy, VAT is 22%. My price is **19.99**
So, price without VAT is **16.38524** and money-rails save it like **1639** in column "price_cents".
The problem comes out when I try to do this operation: 
price_cents+VAT --> 16.39+22% = **19.9958**
(19.9958).round(2) becomes **20.00** that is wrong (initial price **19.99**).

Is there a way to solve this problem?

Thanks in advance.

**Comment by antstorm** [comment]
@S200124 in order to achieve this you might wanna turn the `infinite_precision` on:

```ruby
Money.infinite_precision = true
```

This will give you non-rounded results:

```ruby
>> Money.new(1999.58)
=> #<Money fractional:0.199958E4 currency:USD>
```

As to the actual rounding — I'm no expert in finance, but I think this approach will make you loose money, since you're trying to round down. Anyways, if you're sure that it's correct then try using the `BigDecimal::ROUND_DOWN` rounding mode:

```ruby
>> Money.infinite_precision = false
=> false
>> Money.rounding_mode = BigDecimal::ROUND_DOWN
=> 2
>> Money.new(1999.58)
=> #<Money fractional:1999 currency:USD>
```

**Comment by S200124** [comment]
@antstorm thank you for your reply.

Unfortunately my `infinite_precision` is already `true`.
I think the real problem is how the gem stores the price into db.

I describe you the full operation flow, so you can understand better:
The user insert **19.99** (price with VAT) from web-interface. Let's call it `@price_vat_included`.
So, the system does something like this:

`tax = 0.22`
 `product.price = @price_vat_included.to_f / (1 + tax)`
`product.save`

So, in `product.price` there is **16.38524** (I think). And it is good!
But when the price is stored in DB with `product.save`, in DB `price_cents` becomes **1639** and we lost precision.
If `price_cents` were **16385** the problem would be solved, but since column's name is `_cents` I think it's not possible.

Thanks in advance for your replies.

**Comment by antstorm** [comment]
@S200124 right, so it seems to me that changing the rounding mode in your case should help:

```ruby
>> Money.rounding_mode = BigDecimal::ROUND_DOWN
=> 2
>> @price_vat_included = 19.99
=> 19.99
>> tax = 0.22
=> 0.22
>> product.price = Money.from_amount(@price_vat_included.to_f / (1 + tax))
=> #<Money fractional:1638 currency:USD>
```

The trick is in initializing your `Money` object directly and having your rounding mode set to `ROUND_DOWN`.

**Comment by S200124** [comment]
@antstorm thanks again for your reply.

Unfortunately this trick works with **19.99** but not, for example, with **109.99** because:
```ruby
>> Money.rounding_mode = BigDecimal::ROUND_DOWN
=> 2
>> @price_vat_included = 109.99
=> 109.99
>> tax = 0.22
=> 0.22
>> product.price = Money.from_amount(@price_vat_included.to_f / (1 + tax))
=> #<Money fractional:9015 currency:USD>
```
but
 ```ruby
>> product.price + product.price * tax
=> 109.983
>> 109.983.round(2)
=> 109.98
```
And **109.98** is wrong (initial price **109.99**)

------------------------------------------------------------------------------------

I realized just now that there is a problem even without ROUND_DOWN:
```ruby
>> @price_vat_included = 109.99
=> 109.99
>> tax = 0.22
=> 0.22
>> product.price = Money.from_amount(@price_vat_included.to_f / (1 + tax))
=> #<Money fractional:9016 currency:USD>
>> product.price + product.price * tax
=> 109.9952
>> 109.9952.round(2)
=> 110.0
```
Result **110.00**, from bad to worse.

**Comment by antstorm** [comment]
@S200124 oh, right, you're doing a back and forward conversion and things don't add up. This is impossible with integer column, you'll have to use decimal DB column for that. Usually you don't wanna split pennies, especially when defining a price, because accountancy will have to deal with that somehow.

While this is not tested, I suggest you try switching DB column to `decimal` (while keeping the infinite precision on) and see if that works for you. I'll check that later myself as well.

**Comment by antstorm** [comment]
As an alternative solution you might also wanna use something like:

```ruby
def figure_out_price_before_tax(price_in_cents, tax)
  float_before_tax = price_in_cents.to_f / (1 + tax)

  if (float_before_tax.floor * (1 + tax)).truncate == price_in_cents
    float_before_tax.floor
  else
    float_before_tax.ceil
  end
end
```

although this needs some proper testing first… otherwise it works for both your cases:

```ruby
>> figure_out_price_before_tax 109_99, 0.22
=> 9016
>> (_ * 1.22).floor
=> 10999
```

and

```ruby
>> figure_out_price_before_tax 19_99, 0.22
=> 1639
>> (_ * 1.22).floor
=> 1999
```

**Comment by S200124** [comment]
Ok @antstorm, thank you. I'll try and I'll let you know.

**Comment by S200124** [comment]
Ok @antstorm, your solution is good.
I had to do some little modifications, but now prices seem to work well.

Thanks for your supports.
Have a nice day!

**Comment by tommyalvarez** [comment]
@S200124 what did you end up doing? That custom tailored method or using decimal column + infinite precision ?

**Comment by S200124** [comment]
@tommyalvarez I chose the custom method. In my project that solution works fine.

**Comment by tommyalvarez** [comment]
@S200124 Thanks!

For anyone else reaching here like me, i ended up doing this in an initializer:

```
currencies = Money::Currency.table.dup

  currencies.each do |_code, currency|
    Money::Currency.unregister(currency)
  end

  currencies.each do |_code, currency|
    Money::Currency.register(currency.merge(subunit_to_unit: 10000))
  end
```
