### ISSUE TITLE
$in operator issue

### ISSUE THREAD

**Issue by louisajaca** [RubyMoney/money-rails#453]
I am using mongoid 3 and I am trying to query using an $in operator. $eq would return the correct query:

`{"money_field"=>{:cents=>700, :currency_iso=>"USD"}}`

but $in would generate this query 

`{"money_field"=>{"$in"=>["700.00"]}}`

I was expecting mongoid(?) to return

`{"mowney_field"=>{"$in"=>[{"cents" : 700, "currency_iso":"USD"}]}}`

Has anyone encountered this issue before?

**Comment by antstorm** [comment]
@louisajaca haven't seen this issue before, but it does sound like something's wrong on Mongoid side or in the way you apply the criteria. Can you please share how you call it?

**Comment by louisajaca** [comment]
After investigating again and again, the issue was with how we build the arguments. Thanks for the time @antstorm.
