### ISSUE TITLE
Bug in i18n of delimiter and separator

### ISSUE THREAD

**Issue by wisedevman** [RubyMoney/money-rails#454]
When setting default currency in :eur, delimiter and separator stay the same as US.

In console, by calling
```
> m = Money.new(1000, 'EUR')
> m.format
= "10.00" (should be "10,00")
```
The correct string get out only if I prefix in views the helper humanized_money, but I think the behavior is wrong.

By looking for a bug, I noticed a bug in active_model/validator.rb, at line 54, where I think separator and delimiter i18n keys are reversed. Anyway, fixing it didn't resolve the issue.

```
 def decimal_mark
        character = currency.decimal_mark || '.'
        @_decimal_mark ||= Money.use_i18n ? I18n.t('number.currency.format.separator', default: character) : character
      end

      def thousands_separator
        character = currency.thousands_separator || ','
        @_thousands_separator ||= Money.use_i18n ? I18n.t('number.currency.format.delimiter', default: character) : character
      end
```
should be
```
 def decimal_mark
        character = currency.decimal_mark || '.'
        @_decimal_mark ||= Money.use_i18n ? I18n.t('number.currency.format.delimiter', default: character) : character
      end

      def thousands_separator
        character = currency.thousands_separator || ','
        @_thousands_separator ||= Money.use_i18n ? I18n.t('number.currency.format.separator', default: character) : character
      end
```

Please fix it, thank you. My config is:
```
monetize (1.4.0)
money (6.7.1)
money-rails (1.7.0)
rails (3.2.22)
```

**Comment by antstorm** [comment]
@wisedevman thanks for reporting, I will take a look at this one

**Comment by antstorm** [comment]
@wisedevman So it looks like it wasn't meant to do that in the first place (which is a bit weird):

```ruby
# @example
#   Money.new(100, "USD") #=> "$1.00"
#   Money.new(100, "GBP") #=> "£1.00"
#   Money.new(100, "EUR") #=> "€1.00"
```

You can specify `default_format` in your `money-rails` config instead: 

```
config.default_format = {
  decimal_mark: ','
}
```

**Comment by antstorm** [comment]
As for the `active_model/validator.rb`, it seems like it's just some naming confusion rather than a bug:

- `:separator` - Sets the separator between the units (defaults to “.”).
- `:delimiter` - Sets the thousands delimiter (defaults to “,”).

^ from http://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#M001684

**Comment by wisedevman** [comment]
You're right. After rebuild gems, the error disappeared. You can close the issue.
Thank you, great job.
