### ISSUE TITLE
Infinite Precision and Postgresql decimal

### ISSUE THREAD

**Issue by samstickland** [RubyMoney/money-rails#456]
Hi,

I notice that setting:

`Money.infinite_precision = true`

and the postgresql column to `decimal` seems to allow me to perfectly store fractions of a cent.

But I don't see this documented anywhere in the money-rails gem.

Will it all work as expected, or are there surprises?

**Comment by antstorm** [comment]
@samstickland yeah, it should work as expected — `infinite_precision` will use `BigDecimal` when it can without rounding the results. Although feel free to submit PRs/issues if you find any inconsistencies.

**Comment by samstickland** [comment]
Cool, thanks for the quick answer!

Oh additionally, I notice that if I'm using infinite_precision, but the column type is an integer, that it seems to round even before saving.

For example:

```
[7] pry(main)> li = LineItem.new
=> #<LineItem:0x007fc328d9ac18
[8] pry(main)> li.total = Money.new(100_00.15)
=> #<Money fractional:10000.15 currency:GBP>
[9] pry(main)> li.total
=> #<Money fractional:10000.0 currency:GBP>
```

This is actually very useful behaviour for me, since it means I can control the precision simply by selecting an appropriate column type..

I just wanted to check that it's expected?

**Comment by samstickland** [comment]
Oh Spring, how I hate you. `infinite_precision` was still set to false since the initializer was not rerun. The behaviour I'm seeing now is:

```
[27] pry(main)> si.vat = Money.new(198000.90)
=> #<Money fractional:198000.9 currency:GBP>
[28] pry(main)> si.vat
=> #<Money fractional:198000.0 currency:GBP>
```

i.e. it's truncating.

I imagine this is because everything `amount` is set, it's being copied into the `amount_cents` field, which is being managed as an `integer` by ActiveRecord, because of the database type.
