### ISSUE TITLE
Monetizing Postgres arrays

### ISSUE THREAD

**Issue by cd-rum** [RubyMoney/money-rails#459]
How can I monetize this column? 

`t.integer  "net_annual_positions_cents",       default: [],                array: true`

Is there a way out of the box or is this a pull request?

**Comment by antstorm** [comment]
@cd-rum looks like a PR to me, I'm afraid. What's the intention of using an array for this? To store multiple values or value/currency pairs?

**Comment by cd-rum** [comment]
@antstorm Ah, I was afraid of that. Yes, to the former: multiple values.

**Comment by antstorm** [comment]
@cd-rum yeah, that's a PR :) You also might wanna use the `money` gem directly instead, because it's quite a specific use-case.

**Comment by cd-rum** [comment]
@antstorm Ah yeah, good advice. Thanks.

**Comment by antstorm** [comment]
No worries! I'll close this issue for now.
