### ISSUE TITLE
Helper to use currency ISO code instead of symbol?

### ISSUE THREAD

**Issue by rolodato** [RubyMoney/money-rails#467]
Hi! I don't think this is possible currently, but is there a helper method to display a currency amount with the ISO code? For example `USD 100` instead of `$100` as generated by `money_without_cents_and_with_symbol`.

If not I can submit a PR to add one if it would be helpful. There might be some localization issues though, since in different languages the same amount would be either `USD 100` or `100 USD` according to https://en.wikipedia.org/wiki/ISO_4217#Position_of_ISO_4217_code_in_amounts. Thanks!

**Comment by antstorm** [comment]
Great PR, thanks!

So as for the ISO placement issue — I assume it should always be shown before the amount, right? Do you think it's worth adding this to `money` gem as well?

**Comment by rolodato** [comment]
Thanks :)

One thing I could do to prevent further breaking changes is to rename this helper to `humanized_money_with_iso_prefix` in case we have automatic prefixing in the future. It would be trivial to add `humanized_money_with_iso_suffix` if there's enough interest.

To be honest I'm just getting started with Rails, so I'm not sure what the best approach would be here. The ideal situation for me would be to have a single `humanized_money_with_iso` helper that renders as `USD 100` or `100 USD` depending on a locale setting. What do you think?

**Comment by antstorm** [comment]
I'm just trying to think if I ever seen `100 USD` format used anywhere :) But yeah, you wanna depend the formatting on locale with an option to override this for each individual call.

I think `prefix` / `suffix` should be an option for this method, similar to `symbol_first` option that is currently used for currency symbol.

**Comment by rolodato** [comment]
Yes, having a configurable option seems to make more sense. The best way to implement that would be by adding it to `money`, I'll see if I can set up a PR for that as well.

**Comment by antstorm** [comment]
Great, thank you!

**Comment by rolodato** [comment]
@echan00 Not to my knowledge. I'm just getting back into a Rails project so might have some time to work on this in a few days.
