### ISSUE TITLE
Spec raises a warning

### ISSUE THREAD

**Issue by cd-rum** [RubyMoney/money-rails#469]
With Ruby 2.4.0, and Rails 5, Rspec fails with these issues:

    ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized

That line is printed to my console after running `rspec` about 40 times (there's several monetized columns on my model which might reflect that.

**Comment by antstorm** [comment]
@cd-rum does it actually fail or only prints the warnings out?

It seems like `MoneyRails::ActiveModel::MoneyValidator` was called without `monetize`ing any attributes before that. Any chance of getting a bit more lines from the stack trace?

**Comment by cd-rum** [comment]
@antstorm This is my bad, it's just the warnings. Happy to include the stacktrace if you're curious, it's not a show-stopper though.

**Comment by antstorm** [comment]
@cd-rum great, yeah, that stack trace would be really useful, thanks!

**Comment by cd-rum** [comment]
@antstorm no worries at all!

```
Remote:mirror cdrum$ rspec
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated

Randomized with seed 47882
.../Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:13: warning: instance variable @monetized_attributes not initialized
/Users/cdrum/.rvm/gems/ruby-2.4.0/gems/money-rails-1.7.0/lib/money-rails/active_record/monetizable.rb:189: warning: instance variable @system_price_gross not initialized
```

And it's those lines over and over again for each monetized column, it seems.

**Comment by antstorm** [comment]
@cd-rum thanks, but can you get a slightly deeper trace for these `money-rails/active_record/monetizable.rb:13` warnings? Otherwise it's not clear why these appear…

**Comment by consti** [comment]
I also get a `warning: constant ::Fixnum is deprecated` with Ruby 2.4.0:

```sh
monetize-1.4.0/lib/monetize.rb:87: warning: constant ::Fixnum is deprecated
```

I think this was resolved in [monetize-1.6.0](https://github.com/RubyMoney/monetize/blob/master/CHANGELOG.md)

@antstorm could you please release a new version of `money-rails` that depends on `monetize ~> 1.6.0`? Thanks!

**Comment by antstorm** [comment]
@consti yeah, it isn't merged yet because it needs error handling fixed, but I will do this today/tomorrow.

**Comment by consti** [comment]
@antstorm any news on this? Thanks! :)

**Comment by antstorm** [comment]
@consti sorry, my bad, will aim for releasing it later today. Btw, if you could point your project to `ruby-2-4-0` branch from github and run tests, that would be really helpful! :)

**Comment by antstorm** [comment]
@consti it's out now, version 1.8.0.

@cd-rum any chance of getting that stack trace?

**Comment by consti** [comment]
@antstorm thanks! We got it and everything works smoothly; good work! 👍

**Comment by antstorm** [comment]
Perfect!

@consti try the new version and if the problem still persists — please re-open the issue.
