### ISSUE TITLE
Update fails when String or Hash is supplied in Rails5

### ISSUE THREAD

**Issue by Karolis-Sakavicius** [RubyMoney/money-rails#475]
If I have monetized field (for example "amount") and do `Model.first.update(amount: 12)` or `Model.first.update(amount: Money.new(12, 'USD'))` it works fine but if I supply string or hash it fails silently:
```
2.3.3 :001 > TestModel.first.update(amount: '12 USD')
  TestModel Load (0.1ms)  SELECT  "test_models".* FROM "test_models"  ORDER BY "test_models"."id" ASC LIMIT 1
   (0.1ms)  begin transaction
   (0.0ms)  rollback transaction
 => false
2.3.3 :004 > TestModel.first.update(amount: { cents: 12 })
  TestModel Load (0.2ms)  SELECT  "test_models".* FROM "test_models"  ORDER BY "test_models"."id" ASC LIMIT 1
   (0.0ms)  begin transaction
   (0.0ms)  rollback transaction
 => false
```

If I try to pry at the end of `write_monetized` it looks like it updates model (object) correctly but ActiveRecord's `save` or validations fail. I was able to pinpoint that the culprit is this line in monetizable.rb:222 `instance_variable_set "@#{name}_money_before_type_cast", value`. If I comment it out, everything works fine. I'm not sure what this instance variable is supposed to do, so I do not want to just blindly remove it.

**Comment by antstorm** [comment]
@Karolis-Sakavicius so the instance variable `_before_type_cast` is needed to present user with the original value in case it's invalid after the type cast, so there should be a different solution

**Comment by Karolis-Sakavicius** [comment]
Yes, @antstorm, the validator fails while converting String type to Numeric (validator.rb:30). I think I have the solution - let "monetize" convert user's input to Money and then extract needed number (`fractional` from Money object). As I see the only purpose of lines 25-33 is to extract Numeric value from string.

Validator worked properly with Money objects because `to_s` (line 30) returns only number (`fractional / 100`, without currency iso_code or symbol) and if user supplies integer it's already Numeric. I'll fiddle around with it a bit and make a PR later, so you can check it out. :-)

**Comment by antstorm** [comment]
Yeah, that makes perfect sense @Karolis-Sakavicius. I'm slightly cautious about this solution, because `monetize` has some quirks, but it's probably better than what's currently implemented.

**Comment by Karolis-Sakavicius** [comment]
Monetize doesn't fail when incorrect input is supplied and that's what makes it impossible to use in validator here, unless we modify Monetize to raise an exception when incorrect input is supplied. Now it just creates "empty" Money object (with 0 value & default currency), so validator almost never fails what makes it almost useless. Although README says that `parse!` should raise an exception when Monetize is unable to parse the input but it raises exception only when it cannot recognize supplied currency, not when supplied input is obviously wrong (like "qwerq" string or sth).

Although I believe that money-rails's validator should validate any input that can be successfully converted to Money by Monetize, it is appearently a lot harder to implement than I previously thought.

**Comment by antstorm** [comment]
@Karolis-Sakavicius I guess the first good step towards this would be rethinking the parsing mechanism of the `monetize`, because it's quite naive and inflexible with a lot of issues.

Right now it tries to recognise pretty much predefined format, skipping everything that doesn't fit. I think it was made to be able to find this format in a sentence, which doesn't make much sense. So instead it should probably base it's decisions on multiple formats it knows and throw an error when input doesn't fit.

**Comment by Karolis-Sakavicius** [comment]
Yes, I agree with you @antstorm. It seems like there's no easy fix in `monetize` we could do to make it work with validator here without refactoring whole parsing algorithm. I'll probably try to work on it after wroc_love.rb if no one else wants. I'm very short on time currently. :(

**Comment by antstorm** [comment]
@Karolis-Sakavicius no problem, it's a long standing issue. I'll try to lay out a road map for v2 including changes to the parser. Good luck at wroc_love.rb!

**Comment by Karolis-Sakavicius** [comment]
@antstorm maybe you have a roadmap? I see that you created new repo "money-heuristics", is it related to this problem?

**Comment by antstorm** [comment]
@Karolis-Sakavicius unfortunately no, the `money-heuristics` was extracted from `money` gem and I think is not used by anyone. So currently (knowing all the limitations and recent issues) it seems like both `monetize` and `money-rails` are pending a refactoring work. I'll set a roadmap for both gems and will let you know.
