### ISSUE TITLE
Gem not working on Rails 5.0.2 (helpers can't be found)

### ISSUE THREAD

**Issue by sergio-ocon** [RubyMoney/money-rails#476]
Hi,

I've added the gem to a project to start using it. It is Rails 5.0.2 currently with postgresql 9.4 and Angular as an interface

I've added the gem to my Gemfile and run `bin/rails g money_rails:initializer` and configured it, and when doing the migration I can see the Money and MoneyRails classes, but the migration does not work properly:

It does not recognize monetize in the migration or in the model, so it can't be used

Is that a problem with Rails 5 and ruby 2.3? I've tried to change the t.monetize to bigint, but I still can't get it right.

This is my money.rb

```ruby
# encoding : utf-8
#

require 'money-rails'

MoneyRails.configure do |config|

  # To set the default currency
  #
  # config.default_currency = :usd

  # Set default bank object
  #
  # Example:
  # config.default_bank = EuCentralBank.new

  # Add exchange rates to current money bank object.
  # (The conversion rate refers to one direction only)
  #
  # Example:
  # config.add_rate "USD", "CAD", 1.24515
  # config.add_rate "CAD", "USD", 0.803115

  # To handle the inclusion of validations for monetized fields
  # The default value is true
  #
  # config.include_validations = true

  # Default ActiveRecord migration configuration values for columns:
  #
  config.amount_column = { prefix: '',           # column name prefix
                           postfix: '_cents',    # column name  postfix
                           column_name: nil,     # full column name (overrides prefix, postfix and accessor name)
                           type: :bigint,       # column type
                           present: true,        # column will be created
                           null: false,          # other options will be treated as column options
                           default: 0
                         }
  #
  # config.currency_column = { prefix: '',
  #                            postfix: '_currency',
  #                            column_name: nil,
  #                            type: :string,
  #                            present: true,
  #                            null: false,
  #                            default: 'USD'
  #                          }

  # Register a custom currency
  #
  # Example:
  # config.register_currency = {
  #   :priority            => 1,
  #   :iso_code            => "EU4",
  #   :name                => "Euro with subunit of 4 digits",
  #   :symbol              => "€",
  #   :symbol_first        => true,
  #   :subunit             => "Subcent",
  #   :subunit_to_unit     => 10000,
  #   :thousands_separator => ".",
  #   :decimal_mark        => ","
  # }

  # Specify a rounding mode
  # Any one of:
  #
  # BigDecimal::ROUND_UP,
  # BigDecimal::ROUND_DOWN,
  # BigDecimal::ROUND_HALF_UP,
  # BigDecimal::ROUND_HALF_DOWN,
  # BigDecimal::ROUND_HALF_EVEN,
  # BigDecimal::ROUND_CEILING,
  # BigDecimal::ROUND_FLOOR
  #
  # set to BigDecimal::ROUND_HALF_EVEN by default
  #
  # config.rounding_mode = BigDecimal::ROUND_HALF_UP

  # Set default money format globally.
  # Default value is nil meaning "ignore this option".
  # Example:
  #
  # config.default_format = {
  #   :no_cents_if_whole => nil,
  #   :symbol => nil,
  #   :sign_before_symbol => nil
  # }

  # Set default raise_error_on_money_parsing option
  # It will be raise error if assigned different currency
  # The default value is false
  #
  # Example:
  # config.raise_error_on_money_parsing = false
end
```

My model:
```ruby
class ShowbackCharge < ApplicationRecord
  belongs_to :bucket
  belongs_to :showback_event
  monetize :fixed_price_cents
  moentize :variable_price_cents
end
```

And my migration:
```ruby
class CreateShowbackCharges < ActiveRecord::Migration[5.0]
  def change
    create_table :showback_charges do |t|
      # t.money :fixed_cost, allow_nil: true
      t.bigint :fixed_cost_cents, default: nil
      t.string :fixed_cost_currency, default: 'USD', null: false
      # t.money :variable_cost, allow_nil: true
      t.bigint :variable_cost_cents, default: nil
      t.string :variable_cost_currency, default: 'USD', null: false
      t.belongs_to :showback_bucket, index: true
      t.belongs_to :showback_event, index: true
      t.timestamps
    end
  end
end

```

**Comment by antstorm** [comment]
@sergio-ocon can you please paste the error and stack trace?

**Comment by sergio-ocon** [comment]
```bash
bin/rails g migration ChangeShowbackChargesToMoney
/home/sergio/workspace/devel-manageiq/config/initializers/money.rb:3:in `<top (required)>': uninitialized constant MoneyRails (NameError)
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /home/sergio/.gem/ruby/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/engine.rb:647:in `load_config_initializer'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/engine.rb:611:in `each'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/share/ruby/tsort.rb:228:in `block in tsort_each'
	from /usr/share/ruby/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/share/ruby/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/share/ruby/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `each'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/share/ruby/tsort.rb:415:in `call'
	from /usr/share/ruby/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/share/ruby/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:347:in `each'
	from /usr/share/ruby/tsort.rb:347:in `call'
	from /usr/share/ruby/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/share/ruby/tsort.rb:226:in `tsort_each'
	from /usr/share/ruby/tsort.rb:205:in `tsort_each'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/railtie.rb:193:in `public_send'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/railtie.rb:193:in `method_missing'
	from /home/sergio/workspace/devel-manageiq/config/environment.rb:5:in `<top (required)>'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
' ' '

**Comment by sergio-ocon** [comment]
Sorry, I forgot the require 'money-rails' when testing again.

Perhaps something to add to the initializer.

I will past the error below

**Comment by sergio-ocon** [comment]
NoMethodError: undefined method `monetize' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x0055cee7c63610>
Did you mean?  money
/home/sergio/workspace/devel-manageiq/db/migrate/20170323144231_change_showback_charges_to_money.rb:5:in `block in change'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:438:in `change_table'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:846:in `block in method_missing'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `block in say_with_time'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:815:in `say_with_time'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:835:in `method_missing'
/home/sergio/workspace/devel-manageiq/db/migrate/20170323144231_change_showback_charges_to_money.rb:3:in `change'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:789:in `exec_migration'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:772:in `block in migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:771:in `migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:951:in `migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1214:in `block in execute_migration_in_transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `block in ddl_transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/transactions.rb:211:in `transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1282:in `ddl_transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1213:in `execute_migration_in_transaction'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1185:in `block in migrate_without_lock'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `each'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1184:in `migrate_without_lock'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `block in migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1301:in `with_advisory_lock'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1132:in `migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/home/sergio/.gem/ruby/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/sergio/.gem/ruby/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by sergio-ocon** [comment]
As you can see, the monetize menthod is not found, so I can't use it in the migration

If I create the columns manually, I get the same error later.

**Comment by antstorm** [comment]
@sergio-ocon I'm trying to replicate the error, but can't. So I guess your migration has `t.monetize` in it, right? Which is not what you've pasted. Also your model has a typo in it (line 5), but it seems like it's not related to the error you've posted. Also your DB doesn't match `monetize` definition in the model (`_cost` instead of `_price`).

After following the steps and correcting the typos I was able to get it running without any issues on rails 5.0.2:

```ruby
>> ShowbackCharge.new.fixed_cost
=> #<Money fractional:0 currency:USD>
```

**Comment by sergio-ocon** [comment]
Yes, I tried to replicate the error to add the logs but I have been working on the code for a while, so I created a new migration and used t.monetize to create new tables, thus the error you see.

I will try again and paste the new results here

**Comment by sergio-ocon** [comment]
I needed to require 'money-rails' in application.rb
I required it in money.rb

That is why I was getting the errors.
That require 'money-rails' is not described in the docs.

Thanks for the help @antstorm

**Comment by antstorm** [comment]
@sergio-ocon normally you don't have to do this, Bundler should require it for you. Are you sure it's in your `Gemfile`?

**Comment by sergio-ocon** [comment]
Yes, it is in the Gemfile.

**Comment by sergio-ocon** [comment]
https://github.com/sergio-ocon/manageiq/tree/add_money_gem

You can see the code here.

**Comment by antstorm** [comment]
@sergio-ocon you've specified `:require => false`, which means that you have to explicitly require the gem later on and that's why it didn't work in the first place

**Comment by sergio-ocon** [comment]
thanks! let me try it
