### ISSUE TITLE
decimal for cent

### ISSUE THREAD

**Issue by dieuit07** [RubyMoney/money-rails#478]
Is there any config or customize code for that?
In some purpose of client, field store money should have 6 decimals (float). Column already float type but after monetize, value return just integer

**Comment by antstorm** [comment]
@dieuit07 I haven't tried this, but you can try enabling `infinite_precision` on the `Money`, which will use `BigDecimal` allowing you to store it at a much higher precision

**Comment by antstorm** [comment]
Here's another approach to this problem — https://github.com/RubyMoney/money/issues/667#issuecomment-290967583. You'll still have to store  integers, but they will include a much higher precision.
