### ISSUE TITLE
Can I change the number of exponents on any given column?

### ISSUE THREAD

**Issue by cd-rum** [RubyMoney/money-rails#480]
Dealing with a lot of monetized columns on my model—is there any way to develop a per-column exponent setting?

Because I'm dealing in USD, and I want a column that can save a rate that looks like so: $7.65448.

Is that possible with this gem?

**Comment by antstorm** [comment]
@cd-rum sure thing, it should be possible by registering a new currency using the `Money::Currency.register` method. You can override USD with the same setting, but use `100000` as your `subunit_to_unit`. Obviously you'll have to deal with rounding to cents on your own.

**Comment by cd-rum** [comment]
Ah great! Thanks @antstorm.
