### ISSUE TITLE
Search a money field using AR "where" raises TypeError

### ISSUE THREAD

**Issue by theoo** [RubyMoney/money-rails#488]
## Context
Migrating from `composed_of` to money-rails gem, on Rails 5.0.1

In the model:
```
monetize :value_in_cents, as: 'value'
```

In console, getter/setter are working
```
> singleton = Model.first
> singleton.value = 20.to_money
> puts singleton.value.to_i
=> 20
```
But searching using `where` on the very same attribute raise an error.
```
Model.where(value: 20.to_money)
```

## Expected behaviour
The query should return a `Model::ActiveRecord_Relation` object.

## Current behaviour
The line returns
```
> Model.where(value: 20.to_money)
TypeError: can't cast Money
from /usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/quoting.rb:40:in `rescue in type_cast'
```

## Side note/question
I switch from a working solution with `composed_of` because of an comment announcing the deprecation in Rails 4. (yes, an old comment...)
We can read here http://blog.plataformatec.com.br/2012/06/about-the-composed_of-removal/ that this was subject to discussion, and see that `composed_of` is still available in Rails 5.1 without deprecation warning. http://api.rubyonrails.org/classes/ActiveRecord/Aggregations/ClassMethods.html
Does anyone have any idea what's going to happen with this method in the future?
Should I switch back to my so-simple-but-finaly-working-concern-file and consider that this gem does not allow search on the composed accessors?
```
module MoneyConcern

  def money(name, cents_attr = nil, currency_attr = nil)
    cents_attr     ||= name.to_s + "_in_cents"
    currency_attr ||= name.to_s + "_currency"

    composed_of name,
      :class_name => 'Money',
      :mapping => [[cents_attr, "cents"], [currency_attr, "currency_as_string"]],
      :constructor => Proc.new { |cents, currency| Money.new(cents || 0, currency || Money.default_currency) },
      :converter => Proc.new { |value| value.respond_to?(:to_money) ? value.to_money : raise(ArgumentError, "Can't convert #{value.class} to Money") }
  end

end
```

**Comment by antstorm** [comment]
@theoo as far as I'm concerned this wasn't ever a part of `money-rails`, but it's definitely something others would appreciate. I'll have a look at implementing it, but in case you wanna do it — feel free!

As for the `composed_of` — I think they are deprecating it in favour of the new Attributes API (https://blog.metova.com/rails-5-attributes-api), but I'm not sure. Maybe worth asking in rails/rails :)

**Comment by theoo** [comment]
@antstorm `attribute` doesn't do the job by itself, I see it more like a better `serialize`.
As referenced before, `composed_of` deprecation has been cancelled: https://github.com/rails/rails/pull/6743#issuecomment-27530241

I think this is still the best way to implement the finder, but as `composed_of` has been removed in the early stage of `money-rails` developpement (#17), I won't do a pull-request with it.

**Comment by antstorm** [comment]
@theoo I was thinking more like an `attribute` with a custom underlying type that is masking 2 underlying columns. The key here is consistent API which requires methods for all possible conversions (to DB, from DB and from user input).

I wasn't aware that `composed_of` was used in `money-rails`, thanks for pointing that out.
