### ISSUE TITLE
Default currency not allowing non-cents DB columns it previously created since v1.9.0

### ISSUE THREAD

**Issue by mcoms** [RubyMoney/money-rails#494]
app/models/gift.rb
```ruby
class Gift < ApplicationRecord
  monetize :price_pennies
end
```

config/initializers/money.rb
```
MoneyRails.configure do |config|
  config.default_currency = :gbp
end
```

db/migrate/create_gifts_..._.rb
```
class CreateGifts < ActiveRecord::Migration[5.1]
  def change
    create_table :gifts do |t|
      t.monetize :price
      # ...
  end
end
```

In `money-rails (1.8.0)` this worked perfectly. The migration created a database column, `price_pennies` and Money worked on it to provide `Gift.price`.

In `money-rails (1.9.0)` the following error is raised on boot:

```
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/money-rails-1.9.0/lib/money-rails/active_record/monetizable.rb:53:in `block in monetize': Unable to infer the name of the monetizable attribute for 'price_pennies'. Expected amount column postfix is '_cents'. Use :as option to explicitly specify the name or change the amount column postfix in the initializer. (ArgumentError)
```

**Comment by mcoms** [comment]
For others, the following will unblock you...

```ruby
MoneyRails.configure do |config|
  config.default_currency = :gbp
  config.amount_column = { postfix: '_pence' }
end
```

But ideally, `money-rails` should continue using `_pence` for GBP without having to be explicitly told.

**Comment by antstorm** [comment]
@mcoms so this behaviour was changed in this commit — https://github.com/RubyMoney/money-rails/commit/b7250bec5572e1c5aa01e58a287b3fb1ed4d3969. Now it's no longer inferring the name of the column base on the subunit name of the default currency, instead it only relies on the amount column's postfix (without pluralisation). So changing it to `_pennies` should solve your problem.

**Comment by mcoms** [comment]
Thanks @antstorm, if it's always going to be `_cents` going forward, I'll rename the database columns. Could be worth a note in the `CHANGELOG`? I looked there first before raising an issue.

**Comment by antstorm** [comment]
@mcoms yes it will! 👍
