### ISSUE TITLE
Using aggregate functions on collections

### ISSUE THREAD

**Issue by davetapley** [RubyMoney/money-rails#497]
I _believe_ this is a feature request:

If I have e.g. a `has_many :products` collection, and I wish to get the sum of the `price` field, I believe I have to do this:

```
Money.new store.products.sum(:price_cents)
```

I'd like it if money-rails could automatically do this, is that in scope?

**Comment by antstorm** [comment]
@dukedave that's a very interesting suggestion. Might be quite involved, so it would be great to figure out an API for this to have a estimate on whether it fits in scope. Do you have any ideas?

**Comment by dukedave** [comment]
@antstorm I think the API wouldn't be too complicated:

1. For any `monetize :foo_cents, as: foo`:
1. See if the including class extends [`ActiveRecordCalculations`](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html), if it does:
2. Override `calculate` and:
3. If the `column_name` matches the `foo` field, then:
4. Call `super` with `foo_cents`, and:
5. Wrap the result in a `Money.new`.

**Comment by dukedave** [comment]
Uh, I now realize I just answered your asking for an API with some implementation pseudo-code :joy: 
So, the API would be: Monkey patch `calculate` :wink:

**Comment by antstorm** [comment]
@dukedave yeah, that makes perfect sense. The only thing I'm a bit worried is handling different currencies. Maybe if there's more than one currency in the dataset we can return a hash with amounts grouped by currencies.

**Comment by igneus** [comment]
Don't do this.

Even if monkey-patching wasn't ugly enough in itself: `calculate` is there for aggregate calculations that can be done completely on database level. A Money sum isn't such a calculation - it requires application business logic to be executed (at least check that currencies match). Don't monkey-patch an existing method to handle an operation with totally different semantics.

Also the idea of a sum function returning either a single value if currencies match or a collection if they don't is really ugly. The original intent is making things more straightforward, the result is even more complicated. That's a sufficient indication that the proposed "simplification" shouldn't take place.

**Comment by dukedave** [comment]
@igneus I hear your concerns, I too loathe monkey patching.
I will note that in the plan I outlined above we're not changing the behavior for any existing non-error-throwing semantics, i.e:

* Calling `sum(:foo_cents)` would be unchanged.
* Calling `sum(foo)` would previously have been `ActiveRecord::StatementInvalid`, but now would be an instance of `Money` (or a hash, or whatever).

There will be the additional overhead of checking `column_name == :foo_cents` and dispatching `calculate` to `super`, but I think that'd be negligible next to an inevitable DB call.

---

R.e. returning a collection (or hash), I must confess I hadn't thought about currencies, it's a feature I've never used myself 😊 

However, it is worth noting that the existing `calculate` will return a hash [in some cases](http://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-calculate):

> There are two basic forms of output:
> [...]
> Grouped values: This returns an ordered hash of the values and groups them [...]

**Comment by igneus** [comment]
@dukedave 
> However, it is worth noting that the existing calculate will return a hash in some cases

ok, I wasn't aware of this.

And I must admit that Money sum *grouped by currency* is even possible on the database level. It doesn't mean I like the proposal, but my objections have been proven void.

**Comment by dukedave** [comment]
I've ended up with this snippet, to DRY things up a bit:

```ruby
# config/initializers/monetize_scope.rb

module MonetizeScope
  extend ActiveSupport::Concern

  module ClassMethods
    # Loosely inspired by monetize from the money-rails gem, see:
    # https://github.com/RubyMoney/money-rails/blob/dbcfa0d4d1cddcbea6acadb298efc528300e578b/lib/money-rails/active_record/monetizable.rb#L22
    def monetize_scope(subunit_name)
      name = subunit_name.to_s.sub /_cents$/, ''
      scope name, -> { Money.new public_send(subunit_name) }
    end
  end
end

ActiveRecord::Base.send :include, MonetizeScope
```

This allows me to, e.g:

```ruby
class Product < ActiveRecord::Base
  monetize_scope :total_cents

  def self.total_cents
    sum 'amount_cents'
  end
end

Product.all.total # is a Money instance
```

**Comment by antstorm** [comment]
https://github.com/RubyMoney/money-rails/pull/489

**Comment by ClaudioFloreani** [comment]
If `price` is monetized, why don't just `store.products.sum(&:price)` ?

**Comment by antstorm** [comment]
@ClaudioFloreani this will be very inefficient with lots of records — you're fetching and initializing all of them
