### ISSUE TITLE
Boot Error

### ISSUE THREAD

**Issue by ncarinaoitec** [RubyMoney/money-rails#498]
Hi!
I installed the stable releases, and when I add the require 'money' in app.rb, it's giving me this error:

Boot Error
Something went wrong while loading app.rb
LoadError: cannot load such file -- Money

Thanks!

**Comment by antstorm** [comment]
@ncarinaoitec can you be a bit more specific about your setup? Which Rails version are you running? If you're using Bundler then you don't need to `require 'money'`, it's gonna do that for you
