### ISSUE TITLE
Precision not taken into account at ActiveRecord object creation

### ISSUE THREAD

**Issue by Sylvain** [RubyMoney/money-rails#500]
Context : 
- MoneyRails 1.9.0
- ActiveRecord
- In money initializer: config.default_currency = :eur
- Model Item with price_cents and price_currency columns
- Custom currency EU4 (same as EUR but with 4 decimals like in Readme)

I have a model Item defined like this:

```
class Item < ActiveRecord::Base
  register_currency :eu4
  monetize :price_cents, with_model_currency: :price_currency
end
```

In Console, when I try to create an object, I get the following bug
```
pry(main)> Item.create(price: 1.234567, price_currency: "EU4")
   (0.2ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "items" ("price_cents", "price_currency", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["price_cents", 12300], ["price_currency", "EU4"], ["created_at", "2017-08-25 08:17:13.113543"], ["updated_at", "2017-08-25 08:17:13.113543"]]
   (0.7ms)  COMMIT
=> #<Item:0x007fd19a7e2548
 id: 12,
 price_cents: 12300,
 price_currency: "EU4",
 created_at: Fri, 25 Aug 2017 10:17:13 CEST +02:00,
 updated_at: Fri, 25 Aug 2017 10:17:13 CEST +02:00>
```

So the price is rounded before insertion.

When I update this object with the same value, it works. It is like if the object was first instantiate with a EUR currency then converted to EU4. 

Any idea on how to fix this?

Many thanks by advance!

**Comment by igneus** [comment]
Don't set the "implementation attributes" `price_cents` and `price_currency` directly, but assign a `Money` instance to the "monetized" attribute `price`: `Item.create(price: Money.new(1.234567, :eu4))`

**Comment by Sylvain** [comment]
Thanks for your help @igneus! I provided this use case to be clear, but in my web application, the value will issued by a form. 

I will have something like this in my controller : Item.create(params[:item]) where the params hash contains the attributes like : {price: '1.2345', price_currency: 'eu4'}

It won't be convenient to manually modify the hash before the item creation.

**Comment by igneus** [comment]
In the example you posted you actually set `price` and `price_currency`, i.e. you mix the high-level and low-level attributes.
Have you tried `Item.create(price_cents: 1.234567, price_currency: "EU4")` ? It might work as expected.

**Comment by Sylvain** [comment]
Thanks again for your help. 

It works but in my web application, people are expected to provide the price in the form, not the price_cents. So the data received by the controller and passed to the object will be price and not price_cents, unfortunately.

**Comment by igneus** [comment]
(I have nothing more to offer here.)

**Comment by Sylvain** [comment]
Ok no problem @igneus thanks!

I understand that a model with price defined as a Money object can not be handle transparently by a form because the coercion does not take into account the currency defined. 

I will dive deeper in the code to see what I can do.

**Comment by Sylvain** [comment]
OK I found a way to manage this.

I understood why the object is instantiate with EUR instead of EU4. When the migration is created, it sets a default value as 'EUR' for price_currency. In the Money Rails code, when the price is monetized and with_model_currency is sets, it looks at "price_currency" to infer a currency.
But at this moment, the value returned by price_currency is the default value from the DB, not the one passed as an argument.

My solution was to add an attribute 'currency' in my model (with no default value) and to set : 

`monetize :price_cents, with_model_currency: :currency_or_default

def currency_or_default
  if persisted?
    price_currency
  else
    currency
  end
end
`
instead of 
`monetize :price_cents, with_model_currency: :price_currency`

With that in place, the price is coerced to Money with the right currency at creation.

I close the issue and thanks again @igneus, you helped me figure what was happening.

**Comment by antstorm** [comment]
@Sylvain yes, it's a known issue, discussed here — #491. Basically the problem is that we're setting attributes in sequence, so setting a `price` uses your default currency when figuring out the amount in cents and then it changes the currency, but the precision is already lost. What you wanna do is use a `Money` object when setting your `price`, like this:

```ruby
Item.create price: Money.from_amount(1.234567, "EU4")
```

This way both will get set automatically. Another way around is using `price_cents` when setting the amount.

**Comment by antstorm** [comment]
Oh, just noticed the other replies :) So in case of a form I'd recommend combining your amount and currency into a `Money` object in your controller.
