### ISSUE TITLE
Removing decimal from attribute currency

### ISSUE THREAD

**Issue by amingilani** [RubyMoney/money-rails#503]
I have two columns in my database:

```
monetize :grand_total_cents, allow_nil: true
monetize :grand_total_pkr_cents, allow_nil: true, with_currency: 'PKR'
```
All this does is take the grand total from USD and save it in PKR value as well.

The problem is that PKR, in practice, does not subdivide. We no longer have subunit currency, and when quoting prices, we use whole numbers.

Is there a way for me to edit this to stay whole numbers?

E.g. 

```
# When
grand_total_pkr = 12

# Get this
grand_total_pkr.format #=> "₨12"

# Instead of the current
grand_total_pkr.format #=> "₨12.00"
``

**Comment by antstorm** [comment]
@amingilani I'd suggest defining a copy of the PKR with a subunit to unit ratio of 1 (https://github.com/RubyMoney/money#currency) and using that instead of the normal PKR

**Comment by amingilani** [comment]
Thanks! That fixed it :)
