### ISSUE TITLE
Storage precision independent on currency precision

### ISSUE THREAD

**Issue by chargio** [RubyMoney/money-rails#506]
Hi,

I want to be able to define the storage precision independently of the currency used.

For instance: storage precision is 12 digits, I am using USD, so when showing or writing it, i would use 12 "USD", and that would be converted to the number of digits.

In that way, I can store my information without losing data, while keeping it in Integer with all the benefits.

I've read that you can use US8 to create a new currency and convert between them, and that is what I am using right now, but then I can't use all the currencies without defining an alternative currency for all of them (EU8, US8, etc). Configuration and helpers are quite complicated in this way, while having this scheme would be simpler. 

The other alternative, using Decimal and configuring money for infinite precision, is not what I want, as I want to be defining rates a 0.005 $/minute, even if the result will be given as $5.65 and not $5.645. With the current schema that is not possible, as it will trim to $0.00 when I save. Using an intermediate precision is an strategy I've seen in several financial systems in the past.

On the other hand. Would a PR be accepted with this configuration?

**Comment by antstorm** [comment]
@sergio-ocon yeah, it makes perfect sense to me. Probably it can be achieved by redefining the precisions of the currencies you need (as opposed to adding new fictional currencies).

Did you have a specific implementation in mind? You might need to store the precision alongside the record itself to avoid misinterpreting results on fetch. Also in order not having to define it for every currency you might want to have a relative storage precision, where you'd specify additional precision.

**Comment by sergio-ocon** [comment]
Redefining the precisions should not be needed, as every currency would use the same, it will be stored with whatever precision is configured (and it should always be higher than the maximum
There should be defined new functions to grab the info:
- store the information with the precision configured, or with the precision of the currency (so the behaviour is the same that today)
- get the information with that precision if the customer asks for it
- by default, print the information with the currency precision, but open to show more information (like the 0.005 cents example)

**Comment by sergio-ocon** [comment]
Would I need to modify the Money gem and also this one?
