### ISSUE TITLE
How to use multiple money banks

### ISSUE THREAD

**Issue by phlegx** [RubyMoney/money-rails#510]
Hi!

I want to use multiple money banks. I know how to use one money bank and set this to `default_bank`. But how can I use many different money banks?

**Comment by antstorm** [comment]
@phlegx you should be able to pass in a bank when initialising your `Money` object. It's a third argument — `Money.new 100, 'USD', bank`. Unfortunately money-rails doesn't provide easy access to this attribute, but you should be able to add it manually. It's also a good opportunity for a PR in case you're up for it.

Can you also be a bit more specific about your use case? Why would you want multiple banks?

**Comment by phlegx** [comment]
Thx @antstorm for the reply. Can you please add gem [money-openexchangerates-bank](https://github.com/phlegx/money-openexchangerates-bank) here [RubyMoney/money#currency-exchange](https://github.com/RubyMoney/money#currency-exchange)? Thx

**Comment by antstorm** [comment]
@phlegx sure, but it looks very similar to https://github.com/spk/money-open-exchange-rates. What's the difference?

**Comment by phlegx** [comment]
Yes, it is similar but with a better cache handling, more flexible with more usable methods.

**Comment by antstorm** [comment]
@phlegx I would suggest getting in touch with people maintaining the other project and joining forces. I'm sure they would appreciate your help creating a better gem

**Comment by NBuhinicek** [comment]
Hey @antstorm, I got a similar question. I want to make `default bank` to be tenanted, was hopping for something as you did for the initialisation of currency.

`config.default_currency = -> { Tenant.tenant.currency }`

Any ideas how to tackle that?

**Comment by antstorm** [comment]
@NBuhinicek looking at the source it seems like we do support passing in a block, so your example should totally work

**Comment by NBuhinicek** [comment]
Tried putting it in config as
config.default_bank = -> { SmartBank.new } # this isn't tenanted, but just for check

And then in console:
```ruby
[1] pry(main)> Money.default_bank
=> #<Proc:0x00007f8fe66b2df8@.../config/initializers/money.rb:20 (lambda)>
[2] pry(main)> Money.new(10000, 'HRK')
=> #<Money fractional:10000 currency:HRK>
[3] pry(main)> Money.new(10000, 'HRK').exchange_to('EUR')
NoMethodError: undefined method `exchange_with' for #<Proc:0x00007f8fe66b2df8>
```

**Comment by antstorm** [comment]
@NBuhinicek sorry, my bad, misunderstood your last comment. This is supported for currency, but not that bank. Here's a PR to support it for default_bank as well — https://github.com/RubyMoney/money/pull/946. Would this work for you?

**Comment by NBuhinicek** [comment]
@antstorm no probs

Yeah, that would be great. Strange no one before had a need for this, thanks

**Comment by antstorm** [comment]
Merged. I'll have this included in the next release. Feel free to point to GH for now
