### ISSUE TITLE
Unexpected i18n behaviour

### ISSUE THREAD

**Issue by maran** [RubyMoney/money-rails#512]
Hi guys,

I am pretty sure this is not an issue persé but me misunderstanding how things work. 

I am using EUR as default currency, however I don't want to use any i18n from money-rails by default. I tried setting `Money.use_i18n = false` to this end however it's not doing what I expect.

```
2.4.1 :021 > Money.use_i18n = false
 => false
2.4.1 :022 > Money.new(1000).to_s
 => "10,00"
```

Since I disabled i18n I expected the result to be "10.00". 

How can I achieve the default formatting for all to_s operations so I am in control when to use i18n and when not?

**Comment by antstorm** [comment]
So the decimal mark comes from the currency defaults in case i18n is turned off. In order to have more control over this behaviour use `.format` method:

```ruby
>> Money.new(10_00, 'EUR').to_s
=> "10,00"
>> Money.new(10_00, 'EUR').format(symbol: false, decimal_mark: '.')
=> "10.00"
```

Use can also set `Money.default_formatting_rules` if you need consistent formatting throughout your app:

```ruby
>> Money.default_formatting_rules = { symbol: false, decimal_mark: '.' }
=> {:symbol=>false, :decimal_mark=>"."}
>> Money.new(10_00, 'EUR').format
=> "10.00"
```

Hope this helps

**Comment by maran** [comment]
This was actually what I was looking for. Thanks for clearing that up for me. Appreciate the help 👍
