### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by JulienItard** [RubyMoney/money-rails#513]
hello,

I'd like to use monay 6.10 Could you add a tag to use it ? It's already on master but no tag version

Thanks !

**Comment by antstorm** [comment]
@JulienItard both 6.10.0 and 6.10.1 are up and pushed to RubyGems. I've checked the repo and the tags are there. Can you clarify what exactly are you having issues with?

**Comment by npetkov** [comment]
The current release locks money to 6.9.x. The gemspec has been updated in master to allow 6.10.x versions two months ago, but there is no new gem version since then.

**Comment by antstorm** [comment]
Ah gotcha! Pushed the new 1.10.0 to RubyGems (https://rubygems.org/gems/money-rails).
