### ISSUE TITLE
Clarification: periodically updated exchange rate?

### ISSUE THREAD

**Issue by amingilani** [RubyMoney/money-rails#520]
Hi

I'm running the exchange rate for a currency pair that is volatile, can I periodically call `MoneyRails.configure.add_rate` to update the exchange rate, or run a lookup for the exchange rate during each conversation?

This wasn't outlined in the documentation and I think it should be added. I'll create a PR based on this answer.

**Comment by antstorm** [comment]
I think both approaches can work, it depends on your particular application and where you are fetching the rates from. Calling `add_rate` will probably be a bit more suited to the majority of cases, however you'll need to make sure there are no race conditions in that call, just in case

**Comment by amingilani** [comment]
Thanks @antstorm!
I'm planning on storing the exchange rate in a redis database, updated through a separate service, since the application I'm making converts crypto to fiat, and the latest exchange rate is crucial for every trade.

**Comment by tommyalvarez** [comment]
@amingilani How did you finally call add_rate dynamically from within your application to update the exchange rates ? I need to do it periodically like you or during certain 'user events' where i need to fetch them in real time.
