### ISSUE TITLE
Thousands separator and decimal mark doesn't change

### ISSUE THREAD

**Issue by Leohige** [RubyMoney/money-rails#522]
I'm trying to change the ``thousands_separator`` to ``.`` but it still remains as ``,``. The same for ``decimal_mark``.

My code:

```ruby
  config.register_currency = {
    :priority            => 1,
    :iso_code            => "BRL",
    :name                => "",
    :symbol              => "R$ ",
    :symbol_first        => true,
    :subunit             => "Subcent",
    :subunit_to_unit     => 100,
    :thousands_separator => ".",
    :decimal_mark        => ","
  }
```

**Comment by antstorm** [comment]
@Leohige can you please share more details on this? What makes you think that these attributes don't change?

**Comment by Leohige** [comment]
I'm using the ``humanized_money_with_symbol`` to show the money value, but the ``thousands_separator`` and ``decimal_mark`` never changes, but the ``symbol`` always changes.

My model

```ruby
class Product < ApplicationRecord
  register_currency :BRL

  monetize :purchase_price_cents, with_model_currency: :currency
  monetize :sale_price_cents, with_model_currency: :currency

  belongs_to :brand
end
```

**Comment by tibra** [comment]
I'm also having the issue: the separators are just ignored, ie.:
```
config.register_currency = {
 :priority            => 1,
 :iso_code            => "EUR",
 :name                => "Euro with subunit of 4 digits",
 :symbol              => "€",
 :symbol_first        => true,
 :subunit             => "Cent",
 :subunit_to_unit     => 100,
 :thousands_separator => "#",
 :decimal_mark        => "/"
  }
```
results in €37.200. But I've found a workaround by uncommenting the `default_formats`:
```
config.default_format = {
 :no_cents_if_whole => nil,
 :symbol => nil,
 :sign_before_symbol => nil,
 :thousands_separator => "%",
 :decimal_mark        => "&"
 }
```

This results in €37%200, so the default formats is being used, but the `register_currency` format would still be ignored (but up there in `register_currency`, options like `sign_before_symbol` work just fine).

**Comment by antstorm** [comment]
@tibra what is `Money.locale_backend` set to in your app? It needs to be set to `:currency` to respect settings based on currency. This is however not suggested as it should be driven by locale, not the currency (e.g. people in US would use the same formatting for any currency, not just USD)

**Comment by tibra** [comment]
@antstorm It seems there is no method for it. In this particular app, the gem is locked to v 1.11.0. In another app, this method works and we have the gem at 1.13.1 there.
```
[Rails Console]> Money.locale_backend
NoMethodError: undefined method `locale_backend' for Money:Class
```

I've now upgraded to 1.13.2, resulting in:
```
[Rails Console]> Money.locale_backend
=> #<Money::LocaleBackend::Legacy:0x00007ff2b5305570>
```

**Comment by antstorm** [comment]
@tibra I see, does it work as expected now?
