### ISSUE TITLE
Can I make a PR to update the README for the ':with_currency' option of 'monetize'? 

### ISSUE THREAD

**Issue by ristovskiv** [RubyMoney/money-rails#526]
As I was reading through the code I've noticed that `Attribute Currency (:with_currency)`, besides specifying a currency code as it is currently written, has an option to also accept a [proc, lambda (or any Ruby object that responds to a method named `call`)](https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L282) as it value. As far I can see it is also tested in a couple of situations ([one example](https://github.com/RubyMoney/money-rails/blob/master/spec/active_record/monetizable_spec.rb#L1021) out of many)

My humble opinion is that this is a really cool feature, and while I understand that the gem/engine is not huge, still it would be better if it is elaborated more (with small examples of course) on this.

**Comment by antstorm** [comment]
@ristovskiv I would greatly appreciate you covering these use cases in a README and will gladly accept a PR

**Comment by ristovskiv** [comment]
@anthonator done
https://github.com/RubyMoney/money-rails/pull/527
