### ISSUE TITLE
gem not working with MONGOID

### ISSUE THREAD

**Issue by dinilv** [RubyMoney/money-rails#528]
HI,

while executing this gem with mongoid model, on save we are always facing same error. added only relevant snippet of code and no other issues are thrown

Can we use any other float or digits for passing value ?

MONGO: 3.4.2
MONGOID: 6.4
RAILS: 5.1.4
RUBY: 2.4.2
MONEY-RAILS: 1.0

ERROR:
_ArgumentError (invalid value for BigDecimal(): "{"cents"=>0.123413e2, "currency_iso"=>"EUR"}"):_

CODE:

_model.new.media_cost=Money.new("cents"=>BigDecimal('12.3413'),"currency_iso"=>'EUR')_

MODEL:  
_field :media_cost, :type => Money_

**Comment by antstorm** [comment]
@dinilv you are initialising `Money` with a hash, which is not a valid argument. So instead of:

```ruby
Money.new("cents"=>BigDecimal('12.3413'),"currency_iso"=>'EUR')
```

you should use:

```ruby
Money.new(BigDecimal('12.3413'), 'EUR')
```

**Comment by jattoabdul** [comment]
`with_model_currency:` option doesn't work with rails6 mongoid v7.

```
enumerize :currency, in: [:usd, :ngn, :gbp, :cad], default: :usd, predicates: { prefix: true }
field :price, type: Money, with_model_currency: :currency
```

Getting the following error:
```
Mongoid::Errors::InvalidFieldOption
message:
  Invalid option :with_model_currency provided for field :price.
```
Any help would be appreciated.

**Comment by antstorm** [comment]
@jattoabdul I've just left an answer in your other issue
