### ISSUE TITLE
Update Money to 6.11.1 breaks AR validation

### ISSUE THREAD

**Issue by atitan** [RubyMoney/money-rails#529]
I have a model using `monetize` from money-rails.

After I updated Money from 6.11.0 to 6.11.1, it now fails AR validation.

The errors message says the monetized attribute is not a number.

It seems [this commit](https://github.com/RubyMoney/money/commit/f260b9dc1dcdca28b67f6b3671c04241f0f89fce) changed `Money.new(1000, 'USD').to_s` from "10.00" to "10.00 USD", and Rails is using regex \d to check numericality.

**Comment by antstorm** [comment]
@atitan thanks a lot for pointing this out! It seems like the issue is only evident when certain default formatting rules have been applied. I've just pushed a new version 6.11.2 (https://rubygems.org/gems/money) that should have it fixed.
