### ISSUE TITLE
Issue with locale and decimal separator

### ISSUE THREAD

**Issue by MittchoBaroco** [RubyMoney/money-rails#538]
Hi I am having a issue with validation and the decimal separator.

The app I am doing has two language French and English

On my first try of setting up rails I18n I had the following errors only when I was submitting my form in french.

`Normal price currency not valid: must be a valid currency (e.g.'100','5.24', or'123,456.78'). received 1500.0`

Then I had a parsing to the controller:

```ruby
#fix currency for french locale
    if I18n.locale.eql?(:fr)
      if tour_params[:price_normal].present?
        correct_money_normal = tour_params[:price_normal].gsub(".", ",")
        @tour.price_normal = correct_money_normal
      end

      if tour_params[:price_braaam].present?
        correct_money_braaam = tour_params[:price_braaam].gsub(".", ",")
        @tour.price_braaam = correct_money_braaam
      end
    end
```

I am just wondering if there is a cleaner way to make my input forms works all the time deepening of the currency

I am using rails 5.2

**Comment by MittchoBaroco** [comment]
thanks @antstorm 

so this is my form:
```ruby
<%= form.number_field :price_normal, value: @tour.price_normal.to_f, min: 0, step: 0.01, class: "input" %>
```
and the gem is actually doing the right behaviour on Prod but I still need my parsing on development

**Comment by antstorm** [comment]
@MittchoBaroco hmm, what is actual value being sent to the server on development?

**Comment by MittchoBaroco** [comment]
@antstorm weirdly if I want to form to save the value (in case of a render for example I need to pass the value manually like this).

**Comment by MittchoBaroco** [comment]
@antstorm 

**My params hash (it's the same depending of locale):**
`<ActionController::Parameters {"title"=>"Nino Retrete", "description"=>"Toute l'école argentine du clown concentrée dans un spectacle tout public", "video_uri"=>"https://www.youtube.com/watch?v=HfBB3g02OzU&t=1586s", "housing"=>"1", "catering"=>"1", "tour_artist_name"=>"Nino Retrete", "tour_caption"=>"Clown", "price_normal"=>"1500.0", "price_braaam"=>"900.0", "tour_staff_number"=>"1", "tour_artist_email"=>"niretrete@gmail.com", "tour_artist_phone"=>"", "booking_dates_attributes"=><ActionController::Parameters {"0"=><ActionController::Parameters {"day"=>"2018-08-20", "close"=>"0", "id"=>"4", "_destroy"=>"false"} permitted: true>, "1"=><ActionController::Parameters {"day"=>"2018-08-22", "close"=>"0", "id"=>"5", "_destroy"=>"false"} permitted: true>} permitted: true>} permitted: true>`

**Focus on price:**
`"price_normal"=>"1500.0", "price_braaam"=>"900.0"`

**Comment by skuark** [comment]
@MittchoBaroco Did you find a cleaner approach? Thanks!

**Comment by skuark** [comment]
I've been able to apply a temporal fix monkey patching the money-rails validator in my `money.rb` initializer, to force the `decimal_mark` and the `thousands_separator` when validating the user input.

```ruby
module MoneyRails
  module ActiveModel
    class MoneyValidator < ::ActiveModel::Validations::NumericalityValidator
      private

      def decimal_mark; '.' end
      def thousands_separator; ',' end
    end
  end
end
```

I've combined this hack with the _dirty solution_ I mentioned in #554:

```html+erb
<%= form_for @book do |f| %>
  <%= f.number_field :price, value: f.object.price.to_s.gsub(",", ".") %>
<% end %>
```

**Comment by MittchoBaroco** [comment]
@skuark unfortunalty not yet

**Comment by antstorm** [comment]
FYI, I've opened a PR that will respect your `Money.locale_backend` settings when performing input validations — #567. This might solve some of the problems here
