### ISSUE TITLE
patch release for monetize 1.9.0

### ISSUE THREAD

**Issue by patleb** [RubyMoney/money-rails#539]
Would be nice to have a new release for the dependency version of monetize. There is currently a conflict with the new release of Solidus v2.7.0 which depends on monetize ~> 1.8.

**Comment by antstorm** [comment]
@patleb thanks for reminding, just pushed 1.12.0 with `money` and `monetize` dependencies updated (https://rubygems.org/gems/money-rails)

**Comment by patleb** [comment]
:+1:
