### ISSUE TITLE
add_money after option does not work

### ISSUE THREAD

**Issue by pioz** [RubyMoney/money-rails#540]
On a Rails migration like this:
```
class AddTotalMoneyToOrders < ActiveRecord::Migration[5.2]
  def change
    add_money :orders, :total, after: :size
  end
end
```

The option `after` does not work and the fields `total_cents` and `total_currency` are added after updated_at (at the end).

**Comment by pioz** [comment]
It seems that the option `after` is not documented, but exist and works well with `add_column`.

**Comment by pioz** [comment]
In this line of code https://github.com/RubyMoney/money-rails/blob/6151ca20fe9c44120912523bab763e06da87c10c/lib/money-rails/active_record/migration_extensions/options_extractor.rb#L6

you merge only `options[attribute]`, and in this way you skip the `{ after: :column_name }` option, cause in a migration like this
```
def change
  add_monetize :products, :price, after: :quantity
end
```
`options` is exactly `{ after: :quantity }`.

**Comment by antstorm** [comment]
@pioz I see, that makes sense. Would you be up for fixing this?
