### ISSUE TITLE
Using deprecated Money use_i18n

### ISSUE THREAD

**Issue by noelrappin** [RubyMoney/money-rails#547]
On validation, the gem is throwing the following message:

`[DEPRECATION] `use_i18n` is deprecated - use `Money.locale_backend = :i18n` instead`

**Comment by antstorm** [comment]
@noelrappin thanks for raising this, looking at it 👍

**Comment by Joerg-Seitz** [comment]
Made a pr for it https://github.com/RubyMoney/money-rails/pull/558

**Comment by antstorm** [comment]
@Joerg-Seitz thanks for looking into this! 👍

**Comment by antstorm** [comment]
FYI, #558 is now merged and included in `1.13.1`
