### ISSUE TITLE
Deprecation warnings in gem version 1.13

### ISSUE THREAD

**Issue by armchairdj** [RubyMoney/money-rails#548]
Many thanks for the quick release of 1.13 after I filed [this ticket](https://github.com/RubyMoney/money-rails/issues/545).

I've updated to 1.13 and it works great.

However, there's a deprecation in the `money` gem (version 6.13) that requires attention in the next release, because I still get these warnings every time I use one of the helpers:

    [DEPRECATION] `use_i18n` is deprecated - use `Money.locale_backend = :i18n` instead

Not a show-stopper, but looks like there are a few places in the code and the test suite that need to be updated:

https://github.com/RubyMoney/money-rails/search?q=use_i18n&unscoped_q=use_i18n

I'd be happy to submit a PR to fix if that would help.

**Comment by b-nik** [comment]
There also seem to be deprecations regarding default formatting:

```
[DEPRECATION] `symbol_position:` option is deprecated - use `format` to specify the formatting template.
[DEPRECATION] `symbol_after_without_space:` option is deprecated - use `format` to specify the formatting template.
```

**Comment by antstorm** [comment]
@b-nik this is intentional. Use `format(format: '...')` instead. More info can be found here — https://github.com/RubyMoney/money/blob/master/lib/money/money/formatter.rb#L217-L219

**Comment by antstorm** [comment]
@armchairdj looking at a potential solution, but in case you've got time — would totally appreciate a PR 👍 Also bear in mind I've released Money `6.13.1` that clarifies some of these deprecation messages.

**Comment by armchairdj** [comment]
@antstorm Oh, snap! Adding the following line in an initializer:

    Money.locale_backend = :i18n

... totally removes the hundreds of deprecation warnings I was getting in my logs/spec output.

The expanded deprecation messages, with links, in `money 6.13.1` made it much clearer what was going on. Many thanks. I had assumed the deprecation was because of something hard-coded into `money-rails` but it totally wasn't.

For anyone else getting these messages, if you put the following in your Gemfile:

    gem "money", "~> 6.13.1"
    gem "money-rails", "~> 1.13"

... you'll get the better deprecation warnings with a link to how to resolve those deprecations.

Spoiler alert: The link goes [here](https://github.com/RubyMoney/money#deprecation) and outlines your various options for various use cases. The `Money.locale_backend = :i18n` will not be appropriate for all scenarios.

**Comment by antstorm** [comment]
@armchairdj glad the new version made it clear 👍
