### ISSUE TITLE
Add Mongoid 6.x & Mongoid 7.x specs

### ISSUE THREAD

**Issue by FunkyloverOne** [RubyMoney/money-rails#551]
I was trying to do so on my own, but ended up with an endless loop on bundler require, so I cannot run any mongoid specs at all.
Could someone confirm? I'm running ruby 2.5.1 and bundler 1.17.1.

**Comment by antstorm** [comment]
@FunkyloverOne thank for pointing this out, I've opened a PR — #552

**Comment by FunkyloverOne** [comment]
Amazing, thanks!
