### ISSUE TITLE
Cant run rake in the new version

### ISSUE THREAD

**Issue by luisbrandao** [RubyMoney/money-rails#555]
Hello,
I hadnt to my rails code for almost 3 years, and had come back to it this week...
Money gem is acting up now:

i keep hetting the error:

```
== 20150715163059 ChangePrecoInItens: migrating ===============================
-- remove_column(:itens, :precoE)
   -> 0.1432s
-- add_column("precoE_centavos", {})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

wrong number of arguments (given 2, expected 3..4)
/usr/local/rvm/gems/ruby-2.5.3/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/schema_statements.rb:404:in `add_column'
```

The migration:
```
class ChangePrecoInItens < ActiveRecord::Migration
  def change
    remove_column :itens, :precoE #old column created way before money
    add_money :itens, :precoE, {:null => false, :default => 0, :postfix => '_centavos'}
  end
end
```

my money.rb:

```
  config.default_currency = :BRL
  config.no_cents_if_whole = false

  config.register_currency = {
     :priority            => 1,
     :iso_code            => "BRL",
     :name                => "Real",
     :symbol              => "R$ ",
     :symbol_first        => true,
     :subunit             => "centavo",
     :subunit_to_unit     => 100,
     :thousands_separator => ".",
     :decimal_mark        => ",",
     :amount_column       => '_centavos',  #Does nothing i guess
     :as                  => '_centavos',  #Does nothing i guess
  }
  config.amount_column = { postfix: '_centavos' }

  config.default_format = {
    #:no_cents_if_whole => nil,
    :symbol => "R$ ",
    :sign_before_symbol => true
  }
```

If i remove the config.amount_column = { postfix: '_centavos' } option, the error change to 

`ArgumentError: Unable to infer the name of the monetizable attribute for 'precoE_centavos'. Expected amount column postfix is '_cents'. Use :as option to explicitly specify the name or change the amount column postfix in the initializer.`

How do i use money nowdays? even a fresh rails new is doing that.

Rails: 4.2.10

    monetize (1.9.0)
      money (~> 6.12)
    money (6.13.1)
      i18n (>= 0.6.4, <= 2)
    money-rails (1.13.0)
      activesupport (>= 3.0)
      monetize (~> 1.9.0)
      money (~> 6.13.0)
      railties (>= 3.0)

**Comment by antstorm** [comment]
@luisbrandao terribly sorry for a delay — holidays and all. So it looks like what needs updating here is your migration — nest your options under `amount`:

```ruby
add_money :itens, :precoE, :amount => {:null => false, :default => 0, :postfix => '_centavos'}
```

This will make sure that your inline options are taken into account. But a bigger problem is with `config.amount_column`, which you override with just one value, essentially removing all the other attributes. You'd need something like:

```ruby
config.amount_column = { 
  prefix: '',           # column name prefix
  postfix: '_cents',    # column name  postfix
  column_name: nil,     # full column name (overrides prefix, postfix and accessor name)
  type: :integer,       # column type
  present: true,        # column will be created
  null: false,          # other options will be treated as column options
  default: 0
}
```

feel free to change some of these, but leave all of the keys in place. As an alternative you should be able to just `config.amount_column[:profix] = '_centavos'`.

Hope that helps!
