### ISSUE TITLE
[QUESTION] Is there any way to configure "whitelisted" currencies for rails app?

### ISSUE THREAD

**Issue by FunkyloverOne** [RubyMoney/money-rails#556]
So we could work with only "supported" currencies, and no others?

**Comment by antstorm** [comment]
@FunkyloverOne there's currently no built-in way of doing this, but you can use some sort of a factory or just a wrapper to check. However I'm open to adding this, got some time to throw together a PR?

**Comment by FunkyloverOne** [comment]
Yeah, sure. I already have super basic custom validator for models in my code here:
```ruby
# Validates if currency is allowed on money field
class AllowedCurrencyValidator < ActiveModel::EachValidator
  ALLOWED_CURRENCIES = %w[USD EUR].freeze

  def validate_each(record, attribute, value)
    return if value.nil? || ALLOWED_CURRENCIES.include?(value.currency.to_s)

    record.errors
          .add(attribute, options[:message] || :currency_not_supported)
  end
end
```

But I'm not sure if this is going to work on ActiveRecord models, I'm using it with Mongoid, so I have a special `Money` type, so the `value` here in my code is a `Money` object.

And I'm using it in my models like this:
```ruby
class User
  include Mongoid::Document

  field :balance, type: Money, default: 0
  validates :balance,
            numericality: { greater_than_or_equal_to: 0 },
            allowed_currency: true
end
```

Naming might be better I believe :)

**Comment by FunkyloverOne** [comment]
Hold on, I did a dumb thing, right? :) You got your own money validator, I just didn't see any examples of it's usage with mongoid in your readme... @antstorm

**Comment by antstorm** [comment]
@FunkyloverOne yep, that validator was meant for `ActiveRecord` even though it says it's for `ActiveModel` :) I'm not too familiar with Mongoid's validation and whether it uses `ActiveModel` underneath, but something similar to what you posted looks like a good solution

**Comment by FunkyloverOne** [comment]
@antstorm it does use it underneath, and we already came up with this quite handy validator for Mongoid:
```ruby
# frozen_string_literal: true

class MoneyAmountValidator < ActiveModel::Validations::NumericalityValidator
  def validate_each(record, attr_name, value)
    @record = record
    @attr_name = attr_name
    super
    return unless value && options[:for_currency]

    currency_options = options[:for_currency][value.currency.iso_code]
    return unless currency_options

    buffer_options = options
    @options = currency_options
    super
    @options = buffer_options
  end

  private

  attr_reader :record, :attr_name

  def parse_raw_value_as_a_number(raw_value)
    raw_value = cast_hash_to_money(raw_value) if raw_value.is_a?(Hash)
    return raw_value.amount if raw_value.is_a?(Money)
    super
  end

  def cast_hash_to_money(hash)
    hash = hash.transform_keys(&:to_s)

    unless is_number?(hash['cents'])
      record.errors.add(attr_name, :invalid_cents)
      return nil
    end

    cents = parse_raw_value_as_a_number(hash['cents'])
    Money.new(cents, hash['currency_iso']).amount
  rescue Money::Currency::UnknownCurrency
    record.errors.add(attr_name, :invalid_currency)
    nil
  end
end
```

Which allows us to write code like this:
```ruby
class Tip
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  
  field :gross, type: Money

  # ...

  validates :gross,
            money_amount: {
              greater_than: 0,
              for_currency: {
                'USD' => { greater_than_or_equal_to: 1.5 },
                'RUB' => { greater_than_or_equal_to: 100 }
              }
            }
  # ...
end
```
Which will apply `greater_than: 0` validation for **all** currencies, and also some additional validations for specific currencies.

**Comment by antstorm** [comment]
@FunkyloverOne oh, interesting. Would be open for a PR that makes our current validator compatible with Mongoid or in case these are too different — similar validator that is loaded conditionally

**Comment by FunkyloverOne** [comment]
@antstorm I don't think those two validators could be combined well together...
Well at least I guess it will be easier to start with separate validators for beginning.
Currently I see that our validator for mongoid is missing all the string raw value parsing stuff. I will try to work on some PR later, will see what can be done :)

**Comment by antstorm** [comment]
Sounds good, feel free to ping me an early version of that PR, I'll help you with the direction
