### ISSUE TITLE
It's hard to validate numericality in MongoID

### ISSUE THREAD

**Issue by mltsy** [RubyMoney/money-rails#561]
The built in validations only seem to be included with ActiveRecord, but using MongoId's built-in `numericality` validator raises a Money exception, so there's no easy way to validate numericality of a Money field in MongoID without writing a custom validation method.

**Comment by antstorm** [comment]
@mltsy what is the current behaviour when supplied with an invalid data? From looking at the code it seems like it will raise an error because `Money` will fail to initialize. Or do you need a more specific validation like gte, range, etc?

**Comment by mltsy** [comment]
I was looking for a greater_than validation.  Actually though, it doesn't even raise an exception, if you give it a string like `"moneys"` it will just set the value to 0 (which is very odd).  I think it's calling `to_money` on the string, which for some reason returns a Money of 0 rather than raising an exception.

**Comment by antstorm** [comment]
@mltsy this is odd, agree. I'll put it on my TODO, but feel free to submit a PR meanwhile if you have a solution in mind

**Comment by FunkyloverOne** [comment]
Hey @mltsy , take a look at my custom validator for mongoid I've posted in this comment:
https://github.com/RubyMoney/money-rails/issues/556#issuecomment-447312371

I'm using it in production for a while, it's still missing some fancy parts (like advanced string parsing).

I had no need for that stuff and didn't yet implemented it (I mean when your server receives input in string like `"$99.98"`).
 My server always receives it explicitly, like this "JSON" for example:
`{ cents: 1000, currency_iso: "USD" }`

Feel free to use it as is.

@antstorm what do you think if we will add that validator to this repo as is, (well with some specs of course) and make it clear in documentation that fancy string parsing is not yet implemented for mongoid, PRs are welcome :)

**Comment by mltsy** [comment]
Very nice!  I ended up just using a custom validation method in my case, but that's a real nice validator you got there! ⭐️

**Comment by antstorm** [comment]
@FunkyloverOne sounds great! You wanna give it a shot?
