### ISSUE TITLE
formatting stopped work after upgrade

### ISSUE THREAD

**Issue by luizkowalski** [RubyMoney/money-rails#562]
I have some tests as follow in my app:

```ruby
context 'when sum_with_vat_cents is nil' do
   subject { invoice_item.sum_with_vat_and_with_currency&.orig_format }
      context 'when currency is EUR' do
        let(:i18n_locale) { :de }

        it { is_expected.to eq('€0,00') }
      end

      context 'when currency is PLN' do
        let(:currency) { 'PLN' }
        let(:i18n_locale) { :pl }

        it { is_expected.to eq('0,00 zł') }
        end
      end
    end
```

we updated from 1.8.0 to 1.13.1 (we are in the process to update Ruby and Rails) and now these tests are failing. 

first, `orig_format` doesn't seems to exist anymore and I changed to `format`. 
second, now I don't have the currency symbol anymore when using `format`

```
expected: "0,70 zł"
            got: "0,70"
```

and

```
expected: "€0,70"
            got: "0,70"
```

This is my configuration

```ruby
Money.locale_backend = :currency

MoneyRails.configure do |config|
  # To set the default currency
  #
  config.default_currency = :eur

  #
  config.include_validations = true

  config.currency_column = { prefix: '',
                             postfix: '_currency',
                             column_name: nil,
                             type: :string,
                             present: true,
                             null: true,
                             default: nil }

  config.default_format = {
    no_cents_if_whole: false,
    symbol: nil,
    sign_before_symbol: nil
  }

  # Render cents also when cents part contains zeros only
  config.no_cents_if_whole = false

end
```

I already tried to use different `locale_backend`s, change things under `default_format` but none of these things helped. 

I assume something changed on the API but I couldn't figure it out reading the docs

**Comment by antstorm** [comment]
@luizkowalski sorry to hear that you're having issues. From what I can see — you've got `symbol: nil` specified in the `config.default_format`. This prevents the formatter from outputting the symbol. Has your config changed since `1.8.0`?

**Comment by luizkowalski** [comment]
no, it didn't change

**Comment by antstorm** [comment]
@luizkowalski did removing `symbol: nil` worked for you?

**Comment by luizkowalski** [comment]
no, either with or without `symbol: nil` works. I had to format what I want in place

**Comment by antstorm** [comment]
I had a deeper look at `1.8.0`, trying to figure out what changed since. Couple of findings:

- `orig_format` was never meant to be part of the public interface, it's just aliased `Money#format` that is being slightly modified to accept defaults from your `MoneyRails.configure` call

- calling it directly means that previously all your configuration that wasn't passed in directly was ignored. So the issues is definitely in the way your app is configured

can you tell me what are the values for `MoneyRails::Configuration.symbol` and `MoneyRails::Configuration.default_format` in your app?

**Comment by luizkowalski** [comment]
`MoneyRails::Configuration.symbol`: `nil`

```
[2] pry(main)> MoneyRails::Configuration.default_format
=> {:no_cents_if_whole=>false, :symbol=>nil, :sign_before_symbol=>nil}
```

> orig_format was never meant to be part of the public interface, it's just aliased Money#format that is being slightly modified to accept defaults from your MoneyRails.configure call

that was exactly our problem, there was a snippet in our app calling `orig_format` and our tests broke at that point. I tried to configure it globally (we need two formatting: EUR and PLN) but the formatting through locale didn't work at all so I fall back to call `format` straight in the code instead of having it globally. Our locale_backend is `:currency` now and we format in place

**Comment by antstorm** [comment]
@luizkowalski try changing `symbol` value to `true`, that should instruct the formatter to include a symbol

**Comment by luizkowalski** [comment]
the problem is that we are dealing with two currencies: EUR and PLN. before the upgrade, the whole localization thing was working fine. tried with `symbol: true` but it formats everything to one currency (either EUR or PLN), ignoring the currency set. 

We are going to format these in place from now on. Thanks for the help!

**Comment by antstorm** [comment]
@luizkowalski any chance you can debug it? I'm pretty keen on solving this issue as others might be experiencing it as well

**Comment by luizkowalski** [comment]
@antstorm ok, I can try, give me some days 😄

**Comment by antstorm** [comment]
sure, no problem!
