### ISSUE TITLE
Can not work with attr_accessor

### ISSUE THREAD

**Issue by Uysim** [RubyMoney/money-rails#566]
Example 
```
class Transaction
  include ActiveModel::Model
  include MoneyRails::ActiveRecord::Monetizable

  attr_accessor :amount_cents
  monetize :amount_cents, with_model_currency: :currency

end
```

It can not work because of after_save https://github.com/RubyMoney/money-rails/blob/07dec61e624dbbc6a0662cc5803cb93b8a64505a/lib/money-rails/active_record/monetizable.rb#L148

**Comment by antstorm** [comment]
@Uysim this is a really valid concern as it shouldn't depend on `ActiveRecord`. It has been marked as `TODO`, but never fixed — https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L147. Would you be interested in coming up with a PR?
