### ISSUE TITLE
add locale_backend to configuration template

### ISSUE THREAD

**Issue by ditsara** [RubyMoney/money-rails#569]
From reading the code, it looks like `MoneyRails.configure` delegates `locale_backend`, so you can deal with this issue>(https://github.com/RubyMoney/money#deprecation) within the `configure` block.

Can we add a comment for this setting to `lib/money-rails/configuration.rb` to make this clear to future users? Happy to submit a small PR if requested.

**Comment by antstorm** [comment]
@ditsara yeah, absolutely, happy to merge your PR 👍
