### ISSUE TITLE
Currency object save order

### ISSUE THREAD

**Issue by exadeci** [RubyMoney/money-rails#575]
Similarly to https://github.com/RubyMoney/money-rails/issues/445
```
  monetize :current_amount_cents,
           with_model_currency: :currency
  delegate :currency, to: :account
```

Fails to set the amount:
`Price.create( "current_amount"=>500, "account_id"=>1315)`
Sets the amount correctly:
`Price.create( "account_id"=>1315, "current_amount"=>500)`

A work around I've found is changing the order with strong parameters as my Price is created from an API controller.
```
def create_params
  params.require(:price).permit(:account_id, :current_amount)
end
```

**Comment by antstorm** [comment]
Also raised in #579 

A short term fix seems to be using `current_amount_cents` instead, but you would need to pass in cents instead of dollars (whole units).

But we'll come up with a long-term solution soon, which you are free to help with

**Comment by exadeci** [comment]
Yeah I had noticed that too but it's an API and I can't change the units at will and I prefer not to convert them more than required.
