### ISSUE TITLE
Inconsistent behavior related to memoization

### ISSUE THREAD

**Issue by trushkevich** [RubyMoney/money-rails#578]
Hello!

I have a workflow where an user can setup for a record a currency and amount. Later he can update both currency and amount (for example he can switch from 100 EUR to 0.0001 BTC). Here is the issue. Compare this:
```ruby
[83] pry(main)> mm = MyModel.create(currency: 'EUR', amount_cents: 10000)
=> #<MyModel:0x00007f344d88daf0 id: 1, currency: "EUR", amount_cents: 10000>
[84] pry(main)> mm.amount
=> #<Money fractional:10000 currency:EUR>
[85] pry(main)> mm.update(currency: 'BTC', amount_cents: 10001)
   (1.0ms)  BEGIN
  MyModel Update (1.6ms)  UPDATE "my_models" SET "currency" = $1, "amount_cents" = $2 WHERE "my_models"."id" = $3  [["currency", "BTC"], ["amount_cents", 10001], ["id", 1]]
   (5.3ms)  COMMIT
=> true
[86] pry(main)> mm.amount
=> #<Money fractional:10001 currency:BTC>
```
to this:
```ruby
[57] pry(main)> mm = MyModel.create(currency: 'EUR', amount_cents: 10000)
=> #<MyModel:0x0000564c4788c928 id: 2, currency: "EUR", amount_cents: 10000>
[58] pry(main)> mm.amount
=> #<Money fractional:10000 currency:EUR>
[59] pry(main)> mm.update(currency: 'BTC', amount_cents: 10000)
   (1.0ms)  BEGIN
  MyModel Update (1.7ms)  UPDATE "my_models" SET "currency" = $1, "amount_cents" = $2 WHERE "my_models"."id" = $3 [["currency", "BTC"], ["amount_cents", 10000000000], ["id", 2]]
   (5.1ms)  COMMIT
=> true
[60] pry(main)> mm.amount
=> #<Money fractional:10000000000 currency:BTC>
```
Behavior in the latter example is pretty unexpected obviously. I investigated and found that the issue occurs due to the memoization logic implemented around this line (the one that calculates incorrect amount) https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L197 . So it happens only in 1 specific case - when the cents amounts of both old and new values match and when the currencies differ at the same time. Personally I think that it is better not to decide for a developer about how many cents should be assigned and let him determine himself when a value should be converted to a different currency and when it shouldn't.

ps. I'm using money-rails 1.13.2, rails 5.2.3 with activerecord (pg 1.1.4)

**Comment by antstorm** [comment]
That's a very good catch 👍

There's also a chance that memoization does not really make things much better here, so the path forward might be just getting rid of it. Also the whole idea of a getter method mutating the object should go away if possible.

Definitely happy to review a PR, but tell me if you don't have time and I'll look into this.

**Comment by trushkevich** [comment]
Sorry for such a late response, have been trying to find time, but no luck unfortunately. So probably it will be more efficient if you could take a look at this. (same as #579)
