### ISSUE TITLE
Dependency on the params order

### ISSUE THREAD

**Issue by trushkevich** [RubyMoney/money-rails#579]
This issue is partially linked to the issue https://github.com/RubyMoney/money-rails/issues/578

As a fix for https://github.com/RubyMoney/money-rails/issues/578 my idea was to make this change near https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/active_record/monetizable.rb#L193 :
```diff
        # Dont create a new Money instance if the values haven't been changed.
+        if memoized && memoized.cents == amount && memoized.currency == attr_currency
+          result = memoized
-        if memoized && memoized.cents == amount
-          if memoized.currency == attr_currency
-            result = memoized
-          else
-            memoized_amount = memoized.amount.to_money(attr_currency)
-            write_attribute subunit_name, memoized_amount.cents
-            # Cache the value (it may be nil)
-            result = instance_variable_set("@#{name}", memoized_amount)
-          end
        elsif amount.present?
          # If amount is NOT nil (or empty string) load the amount in a Money
          amount = Money.new(amount, attr_currency)

          # Cache the value (it may be nil)
          result = instance_variable_set("@#{name}", amount)
        end
```
But after that these specs started failing:
https://github.com/RubyMoney/money-rails/blob/master/spec/active_record/monetizable_spec.rb#L80
```ruby
      it "assigns the correct value from params" do
        params_clp = { amount: '20000', tax: '1000', currency: 'CLP' }
        product = Transaction.create(params_clp)
        expect(product.valid?).to be_truthy
        expect(product.amount.currency.subunit_to_unit).to eq(1)
        expect(product.amount_cents).to eq(20000)
      end
```
https://github.com/RubyMoney/money-rails/blob/master/spec/active_record/monetizable_spec.rb#L89
```ruby
      it "re-assigns cents amount when subunit/unit ratio changes preserving amount in units" do
        transaction = Transaction.create(amount: '20000', tax: '1000', currency: 'USD')

        expect(transaction.amount).to eq(Money.new(20000_00, 'USD'))

        transaction.currency = 'CLP'

        expect(transaction.amount).to eq(Money.new(20000, 'CLP'))
        expect(transaction.amount_cents).to eq(20000)
      end
```
```
Failures:

  1) MoneyRails::ActiveRecord::Monetizable.monetize assigns the correct value from params
     Failure/Error: expect(product.amount_cents).to eq(20000)
     
       expected: 20000
            got: 2000000
     
       (compared using ==)
     # ./spec/active_record/monetizable_spec.rb:85:in `block (3 levels) in <top (required)>'

  2) MoneyRails::ActiveRecord::Monetizable.monetize re-assigns cents amount when subunit/unit ratio changes preserving amount in units
     Failure/Error: expect(transaction.amount).to eq(Money.new(20000, 'CLP'))
     
       expected: #<Money fractional:20000 currency:CLP>
            got: #<Money fractional:2000000 currency:CLP>
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -#<Money fractional:20000 currency:CLP>
       +#<Money fractional:2000000 currency:CLP>
       
     # ./spec/active_record/monetizable_spec.rb:96:in `block (3 levels) in <top (required)>'

Finished in 1.06 seconds (files took 0.93408 seconds to load)
254 examples, 2 failures
```
But if I change the params order so that in a params hash the currency would go prior to the amount then it passes
```ruby
      it "assigns the correct value from params" do
        params_clp = { currency: 'CLP', amount: '20000', tax: '1000' }
        product = Transaction.create(params_clp)
        expect(product.valid?).to be_truthy
        expect(product.amount.currency.subunit_to_unit).to eq(1)
        expect(product.amount_cents).to eq(20000)
      end
```
This way I get a green dot from rspec for this example. Also, if I pass `amount_cents` instead of `amount` then specs are also green.

If I understand correctly, money-rails processes params hash key-value pairs one by one, and when it gets to the currency first it assigns it, and later when it gets to the amount it uses correct currency. But when the amount goes first then money-rails uses the default currency (EUR in specs) and since we pass not `amount_cents` but `amount` - it sets cents value according to the currency subunits config (100 subunits per unit in this case). Later when it gets to the currency it just sets it. As a result I get 2_000_000 CLP instead of 20_000 CLP.

So, the primary issue is about the ordered nature of params processing. Also I believe that you should not apply the default currency when some currency is passed in params.

**Comment by antstorm** [comment]
Agree, this is a known, but somewhat not too often seen issue. I think it's worth solving independently of #578. I guess we can store the param that was passed in directly in units (not subunits) and re-asigned the monetized attribute in case currency changes.

Feel free to open another PR or in case you're busy I can pick this one up.

Thanks for raising this, btw 👍

**Comment by trushkevich** [comment]
Sorry for such a late response, have been trying to find time, but no luck unfortunately. So probably it will be more efficient if you could take a look at this.
