### ISSUE TITLE
Best way to localize humanized_money_with_symbol

### ISSUE THREAD

**Issue by 0urobor0s** [RubyMoney/money-rails#580]
The views use `humanized_money_with_symbol @money_object` but it doesn't output the correct format for the current locale.
Option `Money.locale_backend = :i18n` is also set.
To fix this, currently we use `humanized_money_with_symbol @money_object, {format: I18n.t("number.currency.format.format")}` 
Is there a better way to do this? Maybe a new helper `humanized_money_with_symbol_with_locale`?

**Comment by antstorm** [comment]
@0urobor0s version 6 of `Money` doesn't support localizing `format` as there are a few legacy limitations. This will be available once version 7 (https://github.com/RubyMoney/money/pull/872) is released. Hopefully it's not too much of a problem right now

**Comment by 0urobor0s** [comment]
@antstorm no problem, will refactor once version 7 is out
