### ISSUE TITLE
Default serialization introduces breaking changes in minor point release

### ISSUE THREAD

**Issue by stuartgibson** [RubyMoney/money-rails#585]
https://github.com/RubyMoney/money-rails/pull/568

The new default serialization introduced in 1.13.2 -> 1.13.3 breaks any apps that relied on the old default of serializing the complete object. This includes anyone using the common 0.10.x branch of Active Model Serializers, where including the name of the money field would include the whole object, including the currency.

This is against expectation of anyone assuming the versioning follows SemVer.

My use case is rendering objects with money fields as json from the backend API, and having a front end JS service that understands what was the serialized money object to format this on the front end using symbol from the embedded currency object. 
Although I understand the desire to default to a simpler object, doing this in a minor point release seems incorrect.

**Comment by antstorm** [comment]
@stuartgibson thanks for flagging and sorry for breaking this in your app. I really hope you hard specs to catch this before hitting production.

As for the SemVer argument — the PR in question adds a new method that **was not** defined prior to 1.13.3 (1.13.2 raises `undefined method `to_hash' for #<Money>`, as expected). It's pretty hard to take into account all the possible implicit dependencies. So as far this gem is concerned it's debatable whether this was a breaking change or not.

**Comment by theodorton** [comment]
Another breaking change here when a money object is passed to a method wrapped in a `with_options` block. Minimum reproducible example in the following repository: https://github.com/theodorton/money-rails-bug-to-hash
