### ISSUE TITLE
Showing multiple currencies

### ISSUE THREAD

**Issue by benbagley** [RubyMoney/money-rails#586]
I need a little bit of help, I'm looking to show the cost of a collection in multiple currencies, gbp, usd and eur.
I've installed the gem, updated my database and I have GBP price as default and it's showing.

I've added the rate configs

```
config.add_rate "GBP", "USD", 1.29137
config.add_rate "GBP", "EUR", 1.16919
```
and registered the currencies in the model

```
register_currency :gbp
register_currency :usd
register_currency :eur
monetize :price_cents, as: "price", with_currency: :gbp
```

How do I go about showing all three currency prices with the symbols, based on the exchange rate?

**Comment by antstorm** [comment]
@benbagley so `register_currency` is a bit of a poorly named method, but it essentially makes the passed in currency the default currency for all the monetized attributes on your model. It is also expected to be only called once per model, subsequent calls just override the values.

`with_currency` sets the currency value for a specific memoized attribute. In you case this renders previous `register_currency` calls useless (assuming you don't have any other memoized attributes).

If I understand your use case correctly all you need to do is:

```
price_in_gbp = model.price
price_in_eur = price_in_gbp.exchange_to('EUR')
price_in_usd = price_in_gbp.exchange_to('USD')
```

and then use `.format` on these to format the way you need them (there's lots of options available — https://github.com/RubyMoney/money/blob/master/lib/money/money/formatter.rb)
