### ISSUE TITLE
money_without_cents_and_with_symbol uses space instead of &nbsp;

### ISSUE THREAD

**Issue by estani** [RubyMoney/money-rails#587]
money_without_cents_and_with_symbol results in something, e.g. like "27.345 €" with a **normal** space between the number and the symbol. This allows the symbol to be split apart from the number, like this:
![image](https://user-images.githubusercontent.com/1331850/69359924-dca3da00-0c89-11ea-9fd8-2b1dca3ee949.png)

To avoid that the space needs to be replaced by the &nbsp; entity: "27.345&nbsp;€"

That is the sole purpose of the `&nbsp;` entity as "non-breaking space".

I don't think there's a use case for the normal space in html, of course it might for other  use-cases (api, log, etc) so perhaps this should be parametrized?

Is there a workaround for this, besides reimplementing on the application side?

**Comment by antstorm** [comment]
@estani that's a good point and I'm happy to accept a PR that introduces this option.

As for a workaround — you can use `money_without_cents(amount, symbol: true, format: '%n&nbsp;%u')` to achieve this result. Note that with this approach locale will no longer affect the order of number and symbol (it will however affect the number formatting).

**Comment by estani** [comment]
ok, that's a possibility indeed.
Currently, I'm using
```ruby
money_without_cents_and_with_symbol(amount).gsub(' ', '&nbsp;')
```
(or just `"\u00A0"` if not html) which doesn't mess with the position of the symbol.

Actually this is badly implemented in Rails itself, mentioned already in 2008.
I've added an issue there too: https://github.com/rails/rails/issues/37912

Not sure how this gem relates to number_to_currency, perhaps if it's solved there it will be solved here too?

**Comment by estani** [comment]
I followed the rails problem to the centra rails-i18n configurations (which we copied, so I can fixed it for us pretty simply). Pretty much following your advice, but centrally in `active_record.de.yml` changing:
```yml
currency:
  format: "%n %u"
```
to
```yml
currency:
  format: "%n\u00A0%u"
```
And now rails behave properly:
```
HTMLEntities.new.encode(Class.new.extend(ActionView::Helpers::NumberHelper).number_to_currency(12, locale: 'de'), :named)
=> "12,00&nbsp;&euro;"
```

Sadly that's not the case for money-rails:
```
HTMLEntities.new.encode(Class.new.extend(MoneyRails::ActionViewExtension).money_without_cents_and_with_symbol(12), :named)
=> "12 &euro;"
```

I'm still trying to figure out where this is happening, I've tried adding `:format` to the `config.register_currency` configuration, but it just get ignored.

Any hint on where the "default" format is being grabbed from? Not from rails...

**Comment by ruurd** [comment]
From the locale

**Comment by ruurd** [comment]
And why is this unceremoniously closed? No explanation given?

**Comment by semmons99** [comment]
Because it was opened over a year ago and has not seen a subsequent PR. Happy to reopen when there is an associated PR>

**Comment by ruurd** [comment]
Nah, leave as is. It's an underlying problem that the i18n Rails people don't want to fix.
