### ISSUE TITLE
Migration Helper Deprecation Warning (Ruby 2.7.1)

### ISSUE THREAD

**Issue by grdmnt** [RubyMoney/money-rails#598]
When using the migration helper, `t.monetize :field`, and you run `db:migrate`, it raises a deprecating warning.

`/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/money-rails-1.13.3/lib/money-rails/active_record/migration_extensions/table_pg_rails4.rb:8: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

I'm running ruby 2.7.1 with rails 6.0.3.1

**Comment by bsh185** [comment]
Im  facing the same warning as well.

`/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/money-rails-1.13.3/lib/money-rails/active_record/migration_extensions/table_pg_rails4.rb:8: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

**Comment by GoktugOzturk** [comment]
This is caused by a change implemented at ruby 2.7/3.0 

There is a big topic on rubyonrails.org which explains the cause and possible solutions about this. https://discuss.rubyonrails.org/t/new-2-7-3-0-keyword-argument-pain-point/74980

**Comment by antstorm** [comment]
This requires dropping support for older rubies to address. Coordinating a 2.0.0 release that will include the fix

**Comment by ClaudioFloreani** [comment]
> This requires dropping support for older rubies to address. Coordinating a 2.0.0 release that will include the fix

Which ones?

**Comment by antstorm** [comment]
@ClaudioFloreani most likely <= 2.4. Any concerns? These have been EOL for some time now

**Comment by ClaudioFloreani** [comment]
None. Looking forward for 2.0.0

**Comment by ruurd** [comment]
@antstorm when is 2.0.0 coming then?
