### ISSUE TITLE
Rails 6.2 deprecation

### ISSUE THREAD

**Issue by dcangulo** [RubyMoney/money-rails#611]
I am using Rails `6.1.0.rc1` and this deprecation message appears.

```
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead) (called from block in init at /Users/davidangulo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/money-rails-1.13.3/lib/money-rails/hooks.rb:21)
```

Code in question: https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/hooks.rb#L25

**Comment by antstorm** [comment]
@dcangulo interesting… I think this was actually solved in https://github.com/RubyMoney/money-rails/pull/610. Can you check if you're still getting the warning on `master`?

**Comment by dcangulo** [comment]
@antstorm Yes, that PR indeed fixes the warning. When is the next release with that fix included?

**Comment by antstorm** [comment]
@dcangulo glad it worked. Will release one this week

**Comment by jcbpl** [comment]
@antstorm Just bumping this—a new release would be appreciated!

**Comment by ajh-sr** [comment]
> @antstorm Just bumping this—a new release would be appreciated!

Same here 🙂

**Comment by antstorm** [comment]
@jcbpl @ajh-sr just pushed 1.13.4. Sorry for the delay

**Comment by ajh-sr** [comment]
> @jcbpl @ajh-sr just pushed 1.13.4. Sorry for the delay

No worries, thanks for your hard work 🏅 💯
