### ISSUE TITLE
money-rails is marked as incompatible with money 6.14

### ISSUE THREAD

**Issue by iGEL** [RubyMoney/money-rails#628]
`money-rails` depends on `money` with `~> 6.13.2` since [April 2019](https://github.com/RubyMoney/money-rails/commit/405ef311b32b5f4efcf0633a6854f34ac74ca985#diff-dd8524c4dddbfdd97e58f9c3f7865c535e98fe82cfa35c975fbbc72950b36322R29), which doesn't allow the current `money` version. Are you sure you didn't want to write something like `~> 6.13, >= 6.13.2` or `>= 6.13.2, < 6.15` (not exactly sure about the syntax)?

**Comment by iGEL** [comment]
When I wanted to update `money`, `money-rails` and `monetize`, it did this:
```
Installing money 6.14.1 (was 6.13.8)
Installing monetize 1.4.0 (was 1.9.4)
Installing money-rails 1.7.0 (was 1.13.4)
```

**Comment by semmons99** [comment]
happy to accept a PR that does `~> 6.13`

**Comment by dynelight** [comment]
This is still an issue, I tried installing the newest money and forces money-rails to 1.7.

**Comment by rafasoares** [comment]
@semmons99 it looks like a PR has been merged, in fact even [the changelog](https://github.com/RubyMoney/money-rails/blob/main/CHANGELOG.md#1141) has been updated. Any ETA on a release to rubygems.org?

Thanks!
