### ISSUE TITLE
monetized field subunit value incorrect when currency exponent changes during construction

### ISSUE THREAD

**Issue by asavageiv** [RubyMoney/money-rails#645]
```ruby
class Foo < ActiveRecord::Base
  # Use USD as model level currency because it has exponent 2
  register_currency :usd

  monetize :bar_amount, as: :bar, with_model_currency: :bar_currency_code, disable_validation: true
end

f = Foo.new({
  bar: 1,
  bar_currency_code: 'JPY' # exponent 1
})
f.bar_amount # this should be 1, but instead is 100
```

Reading `bar` before saving will fix the `bar_amount`, and putting `bar_currency_code` before `bar` in the initialization hash also prevents the bug.

Demonstrated by this commit with some hacked together tests:
https://github.com/asavageiv/money-rails/commit/187139212180e051d2afbf35b57dd3c60ab9d535

I think the solution to this is to modify the subunit amount when the currency changes for the field or perhaps adding an after_initialize hook that reads the field to fix up the value. Happy to submit a PR if you can guide me on the right approach.

**Comment by asavageiv** [comment]
Looked into this a little more. The `after_initialize` hook doesn't work because the monetized field may be a method that composes other monetized fields that have not yet been set during initialization. E.g. in the tests Transaction#total_cents combines `amount_cents + tax_cents` which aren't necessarily set when the `after_initialize` hook is called.

**Comment by asavageiv** [comment]
This is actually easy to reproduce any time the currency exponent changes.
```ruby
class Product < ActiveRecord::Base
  monetize :price_subunit, as: :price, with_model_currency: :currency
end
```

```
p = Product.new(price: 1, currency: 'USD')
p.price_subunit
=> 100
p.currency = 'JPY'
p.price_subunit
=> 100
p.price
=> #<Money fractional:1 currency:JPY>
p.price_subunit
=> 1
```

I think the solution is to override the currency setter to update the monetized subunit when the currency changes.

**Comment by asavageiv** [comment]
Overriding the currency setter is not quite trivial because multiple attributes can use the same currency model, so all the subunits need to be updated at the same time. I'm trying a different approach by checking if the currency changed when reading the subunit

**Comment by asavageiv** [comment]
@semmons99 Is this fixed or a "will not fix"?

**Comment by semmons99** [comment]
@asavageiv simply a nudge of "if this is still relevant complain it was closed and submit a PR" 😎 

would love to see this reopened with a PR

**Comment by alan-pie** [comment]
PR opened.
