### ISSUE TITLE
:allow_blank not allowed on monetize

### ISSUE THREAD

**Issue by ClaudioFloreani** [RubyMoney/money-rails#671]
In `monetize :price_cents, numericality: { greater_than_or_equal_to: 0}, allow_blank: true`, the :allow_blank option is silently ignored. It leads to confusing "not a number validation errors" which are hard to debug.

**Comment by sunny** [comment]
It would be nice if it raised an error for any unknown option.

**Comment by semmons99** [comment]
please submit a PR to consider changing this
