### ISSUE TITLE
Validation of Currency Types by Name or ISO

### ISSUE THREAD

**Issue by chase-stevens** [RubyMoney/money-rails#679]
I wanted to see if we could set validations on currency columns such that we only allow certain currencies to be initialized as Money objects or saved to currency columns (for example, USD and MXN) and/or disable others (GBP, EUR).

**Comment by sunny** [comment]
In my apps I use something like this for this:

```rb
validates :currency, inclusion: {in: -> %w[USD MXN]}
```

**Comment by chase-stevens** [comment]
Thanks @sunny appreciate it -- think this works for us!
