### ISSUE TITLE
use future default localization behaviour?

### ISSUE THREAD

**Issue by jnicho02** [RubyMoney/money-rails#682]
A clean install on Rails 7.1.2

- money (6.16.0)
- money-rails (1.15.0)

Got a message about i18n

> [DEPRECATION] You are using the default localization behaviour that will change in the next major release. Find out more - https://github.com/RubyMoney/money#deprecation

...which was confusing for a newbie.

Should money-rails default to 'config.locale_backend = :i18n' being on in the initializer, and users override if they want the soon-to-be-deprecated behaviour? Or maybe just a line in the readme to say turn it on?

**Comment by semmons99** [comment]
a line in the readme (PR) seems appropriate for now
