### ISSUE TITLE
Better documentation for numericality validator

### ISSUE THREAD

**Issue by pedroaugustofsilva** [RubyMoney/money-rails#683]
In the monetize below:

```rb
monetize :price_cents,
  allow_nil: true,
  numericality: {
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 10000
  }
```

The values for `greater_than_or_equal_to` and `less_than_or_equal_to` refer to the normalized raw value, not to the value in cents. This is not documented, which can cause some confusion, as it did with me.

Another point is that nil values are converted to 0. In cases where the money cannot be nil, but nil is assigned to it, wouldn't it be better to add an error like "Value can't be blank"?

If these suggestions make sense, I can document them.

**Comment by semmons99** [comment]
please do

**Comment by dchacke** [comment]
It seems more idiomatic to validate the amount in cents.

For example, I enforce a minimum of 5 dollars:

```ruby
monetize :amount_cents,
    numericality: { greater_than_or_equal_to: 5 }
```

But this validation reads as though the minimum amount is 5 *cents*.

The syntax I’d prefer for a 5 dollar minimum is this:

```ruby
monetize :amount_cents,
    numericality: { greater_than_or_equal_to: 500 }
```

This syntax would allow me to consistently use cents on the backend and use dollar amounts only when displaying them to the user.

There’s also the issue of reintroducing floats in validations, eg if the minimum is $5.50. I understand that one reason people use this gem is to avoid floats.

I just started using this gem for the first time recently so forgive me if there’s something I’m missing.
